/**
 * =============================================================================
 * KLYN AI OS — GENESIS v672 — Infinite Intelligence Deployment Network Layer
 * Module: InfiniteDeploymentPlatform.ts (role: platform — composition root)
 * Mission: Deploy intelligence workloads across an unbounded network of nodes with self-healing propagation.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v672` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { IntelligenceDeploymentKernel } from './IntelligenceDeploymentKernel.js';
import { InfiniteDeploymentOrchestrator } from './InfiniteDeploymentOrchestrator.js';
import { DeploymentNetworkRuntime } from './DeploymentNetworkRuntime.js';
import { NetworkDeploymentController } from './NetworkDeploymentController.js';
import { IntelligencePropagationEngine } from './IntelligencePropagationEngine.js';
import { DeploymentNodeRegistry } from './DeploymentNodeRegistry.js';
import { DeploymentCoordinationHub } from './DeploymentCoordinationHub.js';
import { NetworkTelemetryObserver } from './NetworkTelemetryObserver.js';
import { DeploymentEnvironmentAdapter } from './DeploymentEnvironmentAdapter.js';
import type { BootReport } from './InfiniteDeploymentOrchestrator.js';
import type { EngineStats } from './IntelligencePropagationEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v672',
  name: 'Infinite Intelligence Deployment Network Layer',
  codename: 'IntelligenceDeployment',
  version: 'V672',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v672.engine.tick', 'v672.node.joined', 'v672.release.propagated', 'v672.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 4096,
      tickMs: 20,
      batchSize: 96,
      ringSize: 1024,
      consensusThreshold: 0.6,
      compactionThreshold: 0.4,
      quota: 2048,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: IntelligenceDeploymentKernel;
  orchestrator: InfiniteDeploymentOrchestrator;
  runtime: DeploymentNetworkRuntime;
  controller: NetworkDeploymentController;
  engine: IntelligencePropagationEngine;
  registry: DeploymentNodeRegistry;
  coordinator: DeploymentCoordinationHub;
  observer: NetworkTelemetryObserver;
  adapter: DeploymentEnvironmentAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class InfiniteDeploymentPlatform implements LayerModule {
  readonly name = 'InfiniteDeploymentPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new IntelligenceDeploymentKernel(layer, LAYER.codename);
  const orchestrator = new InfiniteDeploymentOrchestrator(layer);
  const runtime = new DeploymentNetworkRuntime(layer);
  const controller = new NetworkDeploymentController(layer, policies);
  const coordinator = new DeploymentCoordinationHub(layer, CONTRACTS, bus);
  const engine = new IntelligencePropagationEngine(layer, policies, bus);
  const registry = new DeploymentNodeRegistry(layer, policies.maxEntities);
  const observer = new NetworkTelemetryObserver(layer, policies.ringSize);
  const adapter = new DeploymentEnvironmentAdapter(layer, CONTRACTS);
  const platform = new InfiniteDeploymentPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
