/**
 * =============================================================================
 * KLYN AI OS — GENESIS v672 — Infinite Intelligence Deployment Network Layer
 * Module: NetworkTelemetryObserver.ts (role: observer)
 * Mission: Deploy intelligence workloads across an unbounded network of nodes with self-healing propagation.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v672` to regenerate.
 * =============================================================================
 */

import { RingBuffer } from '../platform/modules.js';
import type { LayerModule } from '../platform/modules.js';

export interface MetricSummary {
  count: number;
  sum: number;
  min: number;
  max: number;
  avg: number;
  last: number;
}

export class NetworkTelemetryObserver implements LayerModule {
  readonly name = 'NetworkTelemetryObserver';
  readonly role = 'observer';
  readonly layer: string;
  readonly #ringSize: number;
  readonly #rings = new Map<string, RingBuffer<number>>();
  #events = 0;

  constructor(layer: string, ringSize = 256) {
    this.layer = layer;
    this.#ringSize = Math.max(8, ringSize | 0);
  }

  start(): void {}
  stop(): void {}

  record(name: string, value: number): void {
    let ring = this.#rings.get(name);
    if (!ring) {
      ring = new RingBuffer<number>(this.#ringSize);
      this.#rings.set(name, ring);
    }
    ring.push(value);
    this.#events += 1;
  }

  timing(name: string, ms: number): void {
    this.record(name, ms);
  }

  count(name: string): number {
    const ring = this.#rings.get(name);
    return ring ? ring.size : 0;
  }

  last(name: string): number | undefined {
    const ring = this.#rings.get(name);
    return ring ? ring.last() : undefined;
  }

  summary(name: string): MetricSummary | undefined {
    const ring = this.#rings.get(name);
    if (!ring || ring.size === 0) return undefined;
    const values = ring.toArray();
    let sum = 0;
    let min = Number.POSITIVE_INFINITY;
    let max = Number.NEGATIVE_INFINITY;
    for (const value of values) {
      sum += value;
      if (value < min) min = value;
      if (value > max) max = value;
    }
    const count = values.length;
    return {
      count,
      sum,
      min,
      max,
      avg: sum / count,
      last: values[count - 1] as number,
    };
  }

  snapshot(): Record<string, MetricSummary> {
    const out: Record<string, MetricSummary> = {};
    for (const name of this.#rings.keys()) {
      const summary = this.summary(name);
      if (summary) out[name] = summary;
    }
    return out;
  }

  get totalEvents(): number {
    return this.#events;
  }

  reset(): void {
    this.#rings.clear();
    this.#events = 0;
  }
}
