/**
 * =============================================================================
 * KLYN AI OS — GENESIS v676 — Global AI Workflow Civilization Layer
 * Module: AIWorkflowCivilizationPlatform.ts (role: platform — composition root)
 * Mission: A civilization of interoperable workflows spanning teams, systems, and timezones.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v676` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { AIWorkflowCivilizationKernel } from './AIWorkflowCivilizationKernel.js';
import { GlobalWorkflowOrchestrator } from './GlobalWorkflowOrchestrator.js';
import { WorkflowCivilizationRuntime } from './WorkflowCivilizationRuntime.js';
import { WorkflowGovernanceController } from './WorkflowGovernanceController.js';
import { WorkflowExecutionEngine } from './WorkflowExecutionEngine.js';
import { WorkflowStateRegistry } from './WorkflowStateRegistry.js';
import { WorkflowCoordinationHub } from './WorkflowCoordinationHub.js';
import { WorkflowTelemetryObserver } from './WorkflowTelemetryObserver.js';
import { WorkflowIntegrationAdapter } from './WorkflowIntegrationAdapter.js';
import type { BootReport } from './GlobalWorkflowOrchestrator.js';
import type { EngineStats } from './WorkflowExecutionEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v676',
  name: 'Global AI Workflow Civilization Layer',
  codename: 'AIWorkflowCivilization',
  version: 'V676',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v676.engine.tick', 'v676.workflow.started', 'v676.workflow.completed', 'v676.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 8192,
      tickMs: 16,
      batchSize: 128,
      ringSize: 1024,
      consensusThreshold: 0.75,
      compactionThreshold: 0.4,
      quota: 4096,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: AIWorkflowCivilizationKernel;
  orchestrator: GlobalWorkflowOrchestrator;
  runtime: WorkflowCivilizationRuntime;
  controller: WorkflowGovernanceController;
  engine: WorkflowExecutionEngine;
  registry: WorkflowStateRegistry;
  coordinator: WorkflowCoordinationHub;
  observer: WorkflowTelemetryObserver;
  adapter: WorkflowIntegrationAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class AIWorkflowCivilizationPlatform implements LayerModule {
  readonly name = 'AIWorkflowCivilizationPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new AIWorkflowCivilizationKernel(layer, LAYER.codename);
  const orchestrator = new GlobalWorkflowOrchestrator(layer);
  const runtime = new WorkflowCivilizationRuntime(layer);
  const controller = new WorkflowGovernanceController(layer, policies);
  const coordinator = new WorkflowCoordinationHub(layer, CONTRACTS, bus);
  const engine = new WorkflowExecutionEngine(layer, policies, bus);
  const registry = new WorkflowStateRegistry(layer, policies.maxEntities);
  const observer = new WorkflowTelemetryObserver(layer, policies.ringSize);
  const adapter = new WorkflowIntegrationAdapter(layer, CONTRACTS);
  const platform = new AIWorkflowCivilizationPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
