/**
 * =============================================================================
 * KLYN AI OS — GENESIS v696 — AI Civilization Management Layer
 * Module: AICivilizationManagementPlatform.ts (role: platform — composition root)
 * Mission: Govern the civilization itself: domains, policies, growth, and long-horizon stewardship.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v696` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { AICivilizationManagementKernel } from './AICivilizationManagementKernel.js';
import { CivilizationManagementOrchestrator } from './CivilizationManagementOrchestrator.js';
import { AICivilizationRuntime } from './AICivilizationRuntime.js';
import { CivilizationGovernanceController } from './CivilizationGovernanceController.js';
import { CivilizationPolicyEngine } from './CivilizationPolicyEngine.js';
import { CivilizationDomainRegistry } from './CivilizationDomainRegistry.js';
import { CivilizationManagementHub } from './CivilizationManagementHub.js';
import { CivilizationTelemetryObserver } from './CivilizationTelemetryObserver.js';
import { CivilizationSystemAdapter } from './CivilizationSystemAdapter.js';
import type { BootReport } from './CivilizationManagementOrchestrator.js';
import type { EngineStats } from './CivilizationPolicyEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v696',
  name: 'AI Civilization Management Layer',
  codename: 'AICivilizationManagement',
  version: 'V696',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v696.engine.tick', 'v696.domain.admitted', 'v696.policy.enforced', 'v696.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 1024,
      tickMs: 40,
      batchSize: 48,
      ringSize: 256,
      consensusThreshold: 0.66,
      compactionThreshold: 0.55,
      quota: 512,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: AICivilizationManagementKernel;
  orchestrator: CivilizationManagementOrchestrator;
  runtime: AICivilizationRuntime;
  controller: CivilizationGovernanceController;
  engine: CivilizationPolicyEngine;
  registry: CivilizationDomainRegistry;
  coordinator: CivilizationManagementHub;
  observer: CivilizationTelemetryObserver;
  adapter: CivilizationSystemAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class AICivilizationManagementPlatform implements LayerModule {
  readonly name = 'AICivilizationManagementPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new AICivilizationManagementKernel(layer, LAYER.codename);
  const orchestrator = new CivilizationManagementOrchestrator(layer);
  const runtime = new AICivilizationRuntime(layer);
  const controller = new CivilizationGovernanceController(layer, policies);
  const coordinator = new CivilizationManagementHub(layer, CONTRACTS, bus);
  const engine = new CivilizationPolicyEngine(layer, policies, bus);
  const registry = new CivilizationDomainRegistry(layer, policies.maxEntities);
  const observer = new CivilizationTelemetryObserver(layer, policies.ringSize);
  const adapter = new CivilizationSystemAdapter(layer, CONTRACTS);
  const platform = new AICivilizationManagementPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
