/**
 * =============================================================================
 * KLYN AI OS — GENESIS v688 — Intelligent Digital Ecosystem Layer
 * Module: DigitalEcosystemKernel.ts (role: kernel)
 * Mission: A living ecosystem of products, partners, and agents that co-evolve under shared rules.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v688` to regenerate.
 * =============================================================================
 */

import { Logger } from '../platform/modules.js';
import type { LayerModule } from '../platform/modules.js';

export interface KernelRecord {
  name: string;
  role: string;
  status: 'registered' | 'started' | 'stopped';
  registeredAt: number;
}

export interface KernelHealth {
  ready: boolean;
  registered: number;
  started: number;
  stopped: number;
}

export class DigitalEcosystemKernel implements LayerModule {
  readonly name = 'DigitalEcosystemKernel';
  readonly role = 'kernel';
  readonly layer: string;
  readonly codename: string;
  readonly #records = new Map<string, KernelRecord>();
  readonly #log: Logger;
  #bootStartedAt = 0;

  constructor(layer: string, codename: string, quiet = false) {
    this.layer = layer;
    this.codename = codename;
    this.#log = new Logger(layer + ':' + this.role, quiet ? 3 : 1);
  }

  start(): void {
    this.#bootStartedAt = Date.now();
    this.#log.info('kernel module started');
  }

  stop(): void {
    this.#log.info('kernel module stopped');
  }

  register(module: LayerModule): KernelRecord {
    const existing = this.#records.get(module.name);
    const record: KernelRecord = {
      name: module.name,
      role: module.role,
      status: existing ? existing.status : 'registered',
      registeredAt: existing ? existing.registeredAt : Date.now(),
    };
    this.#records.set(module.name, record);
    return record;
  }

  markStarted(name: string): void {
    const record = this.#records.get(name);
    if (record) record.status = 'started';
  }

  markStopped(name: string): void {
    const record = this.#records.get(name);
    if (record) record.status = 'stopped';
  }

  get size(): number {
    return this.#records.size;
  }

  names(): string[] {
    return [...this.#records.keys()];
  }

  records(): KernelRecord[] {
    return [...this.#records.values()];
  }

  bootStartedAt(): number {
    return this.#bootStartedAt;
  }

  health(): KernelHealth {
    let started = 0;
    let stopped = 0;
    for (const record of this.#records.values()) {
      if (record.status === 'started') started += 1;
      if (record.status === 'stopped') stopped += 1;
    }
    const registered = this.#records.size;
    return { ready: registered > 0 && started === registered, registered, started, stopped };
  }

  destroy(): void {
    this.#records.clear();
  }
}
