/**
 * =============================================================================
 * KLYN AI OS — GENESIS v688 — Intelligent Digital Ecosystem Layer
 * Module: EcosystemTopologyOrchestrator.ts (role: orchestrator)
 * Mission: A living ecosystem of products, partners, and agents that co-evolve under shared rules.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v688` to regenerate.
 * =============================================================================
 */

import { Logger, monotonic } from '../platform/modules.js';
import type { LayerModule } from '../platform/modules.js';

export interface BootReport {
  order: string[];
  totalMs: number;
  failures: string[];
}

export class EcosystemTopologyOrchestrator implements LayerModule {
  readonly name = 'EcosystemTopologyOrchestrator';
  readonly role = 'orchestrator';
  readonly layer: string;
  readonly #log: Logger;

  constructor(layer: string, quiet = false) {
    this.layer = layer;
    this.#log = new Logger(layer + ':' + this.role, quiet ? 3 : 1);
  }

  start(): void { /* orchestrator lifecycle is driven by the platform handle */ }
  stop(): void { /* orchestrator lifecycle is driven by the platform handle */ }

  async boot(modules: LayerModule[], order: string[]): Promise<BootReport> {
    const failures: string[] = [];
    const startedAt = monotonic();
    for (const name of order) {
      let found: LayerModule | undefined;
      for (const module of modules) {
        if (module.name === name) { found = module; break; }
      }
      if (!found) { failures.push('missing:' + name); continue; }
      try {
        await found.start();
      } catch (err) {
        failures.push(name + ':' + String(err));
      }
    }
    const totalMs = Math.round((monotonic() - startedAt) * 100) / 100;
    if (failures.length > 0) this.#log.warn('boot failures: ' + failures.join(', '));
    return { order: [...order], totalMs, failures };
  }

  async shutdown(modules: LayerModule[]): Promise<void> {
    for (let i = modules.length - 1; i >= 0; i -= 1) {
      const module = modules[i];
      if (!module) continue;
      try {
        await module.stop();
      } catch {
        /* best-effort shutdown */
      }
    }
  }
}
