/**
 * =============================================================================
 * KLYN AI OS — GENESIS v688 — Intelligent Digital Ecosystem Layer
 * Module: IntelligentDigitalEcosystemPlatform.ts (role: platform — composition root)
 * Mission: A living ecosystem of products, partners, and agents that co-evolve under shared rules.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v688` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { DigitalEcosystemKernel } from './DigitalEcosystemKernel.js';
import { EcosystemTopologyOrchestrator } from './EcosystemTopologyOrchestrator.js';
import { DigitalEcosystemRuntime } from './DigitalEcosystemRuntime.js';
import { EcosystemGovernanceController } from './EcosystemGovernanceController.js';
import { EcosystemGrowthEngine } from './EcosystemGrowthEngine.js';
import { EcosystemEntityRegistry } from './EcosystemEntityRegistry.js';
import { EcosystemCoordinationHub } from './EcosystemCoordinationHub.js';
import { EcosystemTelemetryObserver } from './EcosystemTelemetryObserver.js';
import { EcosystemIntegrationAdapter } from './EcosystemIntegrationAdapter.js';
import type { BootReport } from './EcosystemTopologyOrchestrator.js';
import type { EngineStats } from './EcosystemGrowthEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v688',
  name: 'Intelligent Digital Ecosystem Layer',
  codename: 'DigitalEcosystem',
  version: 'V688',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v688.engine.tick', 'v688.entity.joined', 'v688.symbiosis.formed', 'v688.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 16384,
      tickMs: 20,
      batchSize: 96,
      ringSize: 1024,
      consensusThreshold: 0.7,
      compactionThreshold: 0.45,
      quota: 8192,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: DigitalEcosystemKernel;
  orchestrator: EcosystemTopologyOrchestrator;
  runtime: DigitalEcosystemRuntime;
  controller: EcosystemGovernanceController;
  engine: EcosystemGrowthEngine;
  registry: EcosystemEntityRegistry;
  coordinator: EcosystemCoordinationHub;
  observer: EcosystemTelemetryObserver;
  adapter: EcosystemIntegrationAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class IntelligentDigitalEcosystemPlatform implements LayerModule {
  readonly name = 'IntelligentDigitalEcosystemPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new DigitalEcosystemKernel(layer, LAYER.codename);
  const orchestrator = new EcosystemTopologyOrchestrator(layer);
  const runtime = new DigitalEcosystemRuntime(layer);
  const controller = new EcosystemGovernanceController(layer, policies);
  const coordinator = new EcosystemCoordinationHub(layer, CONTRACTS, bus);
  const engine = new EcosystemGrowthEngine(layer, policies, bus);
  const registry = new EcosystemEntityRegistry(layer, policies.maxEntities);
  const observer = new EcosystemTelemetryObserver(layer, policies.ringSize);
  const adapter = new EcosystemIntegrationAdapter(layer, CONTRACTS);
  const platform = new IntelligentDigitalEcosystemPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
