/**
 * =============================================================================
 * KLYN AI OS — GENESIS v691 — Advanced Intelligence Coordination Layer
 * Module: AdvancedIntelligenceCoordinationPlatform.ts (role: platform — composition root)
 * Mission: Synchronize distributed intelligence units through consensus and coordination protocols.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v691` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { IntelligenceCoordinationKernel } from './IntelligenceCoordinationKernel.js';
import { CoordinationMeshOrchestrator } from './CoordinationMeshOrchestrator.js';
import { IntelligenceCoordinationRuntime } from './IntelligenceCoordinationRuntime.js';
import { CoordinationGovernanceController } from './CoordinationGovernanceController.js';
import { ConsensusEngine } from './ConsensusEngine.js';
import { CoordinationUnitRegistry } from './CoordinationUnitRegistry.js';
import { IntelligenceCoordinationHub } from './IntelligenceCoordinationHub.js';
import { CoordinationTelemetryObserver } from './CoordinationTelemetryObserver.js';
import { CoordinationProtocolAdapter } from './CoordinationProtocolAdapter.js';
import type { BootReport } from './CoordinationMeshOrchestrator.js';
import type { EngineStats } from './ConsensusEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v691',
  name: 'Advanced Intelligence Coordination Layer',
  codename: 'IntelligenceCoordination',
  version: 'V691',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v691.engine.tick', 'v691.unit.synced', 'v691.consensus.reached', 'v691.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 16384,
      tickMs: 16,
      batchSize: 128,
      ringSize: 1024,
      consensusThreshold: 0.85,
      compactionThreshold: 0.35,
      quota: 8192,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: IntelligenceCoordinationKernel;
  orchestrator: CoordinationMeshOrchestrator;
  runtime: IntelligenceCoordinationRuntime;
  controller: CoordinationGovernanceController;
  engine: ConsensusEngine;
  registry: CoordinationUnitRegistry;
  coordinator: IntelligenceCoordinationHub;
  observer: CoordinationTelemetryObserver;
  adapter: CoordinationProtocolAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class AdvancedIntelligenceCoordinationPlatform implements LayerModule {
  readonly name = 'AdvancedIntelligenceCoordinationPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new IntelligenceCoordinationKernel(layer, LAYER.codename);
  const orchestrator = new CoordinationMeshOrchestrator(layer);
  const runtime = new IntelligenceCoordinationRuntime(layer);
  const controller = new CoordinationGovernanceController(layer, policies);
  const coordinator = new IntelligenceCoordinationHub(layer, CONTRACTS, bus);
  const engine = new ConsensusEngine(layer, policies, bus);
  const registry = new CoordinationUnitRegistry(layer, policies.maxEntities);
  const observer = new CoordinationTelemetryObserver(layer, policies.ringSize);
  const adapter = new CoordinationProtocolAdapter(layer, CONTRACTS);
  const platform = new AdvancedIntelligenceCoordinationPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
