/**
 * =============================================================================
 * KLYN AI OS — Offline Task Registry
 * File: kernel/src/execution/offline_task_registry.js
 * Version: 1.0.0
 * =============================================================================
 *
 * PURPOSE:
 *   Central registry of pre-compiled task templates for local compilation.
 *   Each template is a parameterized Bash script that can run offline.
 *
 * =============================================================================
 */

'use strict';

const { createLogger } = require('../observability/logger');

const log = createLogger('OfflineTaskRegistry');

class OfflineTaskRegistry {
  [key: string]: any;

  constructor() {
    /**
     * Task templates. Key = taskType, Value = template object.
     * @type {Map<string, object>}
     */
    this._templates = new Map();

    this._registerDefaultTemplates();

    log.info('Offline Task Registry initialized.', {
      templateCount: this._templates.size,
    });
  }

  /**
   * Registers a new task template.
   * @param {string} taskType
   * @param {object} template
   */
  registerTemplate(taskType, template) {
    this._templates.set(taskType, template);
  }

  /**
   * Retrieves a task template by type.
   * @param {string} taskType
   * @returns {object|null}
   */
  getTemplate(taskType) {
    return this._templates.get(taskType) ?? null;
  }

  /**
   * Returns all registered task types.
   * @returns {string[]}
   */
  getTaskTypes() {
    return [...this._templates.keys()];
  }

  // ---------------------------------------------------------------------------
  // PRIVATE — DEFAULT TEMPLATES
  // ---------------------------------------------------------------------------

  _registerDefaultTemplates() {

    // -------------------------------------------------------------------------
    // SCAN_FILE: Static analysis and vulnerability scanning
    // -------------------------------------------------------------------------
    this.registerTemplate('SCAN_FILE', {
      description: 'Static analysis and vulnerability scan of a source file.',
      parameters: {
        filePath: {
          required: true,
          extractionPattern: 'scan\\s+(?:file\\s+)?["\']?([^"\'\\s]+)',
          default: null,
        },
      },
      scriptTemplate: `
# Target file
FILE_PATH='{{filePath}}'

if [[ ! -f "$FILE_PATH" ]]; then
  log "ERROR: File not found: $FILE_PATH"
  exit 1
fi

log "Scanning file: $FILE_PATH"

# Count lines of code
LOC=$(wc -l < "$FILE_PATH")
log "Lines of code: $LOC"

# Search for common vulnerability patterns
FINDINGS=0

# Pattern 1: eval() usage
if grep -nE '\\beval\\s*\\(' "$FILE_PATH" > /dev/null 2>&1; then
  log "VULN: Found eval() usage (code injection risk)"
  grep -nE '\\beval\\s*\\(' "$FILE_PATH"
  FINDINGS=$((FINDINGS + 1))
fi

# Pattern 2: exec() usage
if grep -nE '\\bexec\\s*\\(' "$FILE_PATH" > /dev/null 2>&1; then
  log "VULN: Found exec() usage (command injection risk)"
  grep -nE '\\bexec\\s*\\(' "$FILE_PATH"
  FINDINGS=$((FINDINGS + 1))
fi

# Pattern 3: Hardcoded credentials
if grep -niE '(password|api_?key|secret)\\s*=\\s*["\'][^"\']+' "$FILE_PATH" > /dev/null 2>&1; then
  log "VULN: Possible hardcoded credentials"
  grep -niE '(password|api_?key|secret)\\s*=\\s*["\'][^"\']+' "$FILE_PATH"
  FINDINGS=$((FINDINGS + 1))
fi

# Pattern 4: TODO/FIXME markers
TODO_COUNT=$(grep -cE '(TODO|FIXME|HACK|XXX)' "$FILE_PATH" 2>/dev/null || echo 0)
if [[ $TODO_COUNT -gt 0 ]]; then
  log "INFO: Found $TODO_COUNT code debt markers (TODO/FIXME/HACK)"
fi

log "Scan complete. Total findings: $FINDINGS"
echo "$FINDINGS"
`,
    });

    // -------------------------------------------------------------------------
    // GENERATE_CODE: Template-based code scaffolding
    // -------------------------------------------------------------------------
    this.registerTemplate('GENERATE_CODE', {
      description: 'Generate code scaffold from template.',
      parameters: {
        templateType: {
          required: true,
          extractionPattern: 'generate\\s+(\\w+)\\s+',
          default: 'function',
        },
        outputPath: {
          required: true,
          extractionPattern: 'output\\s+(?:to\\s+)?["\']?([^"\'\\s]+)',
          default: './output.js',
        },
      },
      scriptTemplate: `
# Generate code scaffold
TEMPLATE_TYPE='{{templateType}}'
OUTPUT_PATH='{{outputPath}}'

log "Generating $TEMPLATE_TYPE scaffold to $OUTPUT_PATH"

case "$TEMPLATE_TYPE" in
  function)
    cat > "$OUTPUT_PATH" << 'EOF'
/**
 * Auto-generated function scaffold
 * Generated by KLYN AI OS
 */

function generatedFunction(param1, param2) {
  // TODO: Implement function logic
  return null;
}

module.exports = { generatedFunction };
EOF
    ;;

  class)
    cat > "$OUTPUT_PATH" << 'EOF'
/**
 * Auto-generated class scaffold
 * Generated by KLYN AI OS
 */

class GeneratedClass {
  [key: string]: any;
  constructor(options: any = {}) {
    this._options = options;
  }

  // TODO: Add methods here
}

module.exports = { GeneratedClass };
EOF
    ;;

  *)
    log "ERROR: Unknown template type: $TEMPLATE_TYPE"
    exit 1
    ;;
esac

log "Code generated successfully at $OUTPUT_PATH"
`,
    });

    // -------------------------------------------------------------------------
    // REFACTOR_CODE: Pattern-based code transformation
    // -------------------------------------------------------------------------
    this.registerTemplate('REFACTOR_CODE', {
      description: 'Apply automated refactoring patterns.',
      parameters: {
        filePath: {
          required: true,
          extractionPattern: 'refactor\\s+["\']?([^"\'\\s]+)',
          default: null,
        },
        pattern: {
          required: false,
          extractionPattern: 'pattern\\s+["\']([^"\']+)',
          default: 'console.log',
        },
      },
      scriptTemplate: `
# Refactoring target
FILE_PATH='{{filePath}}'
PATTERN='{{pattern}}'

if [[ ! -f "$FILE_PATH" ]]; then
  log "ERROR: File not found: $FILE_PATH"
  exit 1
fi

log "Refactoring $FILE_PATH (pattern: $PATTERN)"

# Backup original
cp "$FILE_PATH" "$FILE_PATH.backup"

# Example: Remove all console.log statements
if [[ "$PATTERN" == "console.log" ]]; then
  sed -i '/console\\.log(/d' "$FILE_PATH"
  REMOVED=$(diff "$FILE_PATH.backup" "$FILE_PATH" | grep -c '^<' || echo 0)
  log "Removed $REMOVED console.log statements"
fi

log "Refactoring complete. Backup saved to $FILE_PATH.backup"
`,
    });
  }
}

// =============================================================================
// SINGLETON
// =============================================================================

let _registryInstance = null;

function getOfflineTaskRegistry() {
  if (!_registryInstance) {
    _registryInstance = new OfflineTaskRegistry();
  }
  return _registryInstance;
}

module.exports = Object.freeze({
  getOfflineTaskRegistry,
  OfflineTaskRegistry,
});


export {};
