/**
 * =============================================================================
 * KLYN AI OS — GENESIS v674 — Autonomous AI Engineering Factory Layer
 * Module: AIEngineeringFactoryPlatform.ts (role: platform — composition root)
 * Mission: A continuous-production factory that designs, builds, tests, and ships software with zero human tickets.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v674` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { AIEngineeringFactoryKernel } from './AIEngineeringFactoryKernel.js';
import { FactoryPipelineOrchestrator } from './FactoryPipelineOrchestrator.js';
import { EngineeringFactoryRuntime } from './EngineeringFactoryRuntime.js';
import { FactoryQualityController } from './FactoryQualityController.js';
import { AssemblyLineEngine } from './AssemblyLineEngine.js';
import { ProductionOrderRegistry } from './ProductionOrderRegistry.js';
import { FactoryCoordinationHub } from './FactoryCoordinationHub.js';
import { FactoryTelemetryObserver } from './FactoryTelemetryObserver.js';
import { ToolchainEnvironmentAdapter } from './ToolchainEnvironmentAdapter.js';
import type { BootReport } from './FactoryPipelineOrchestrator.js';
import type { EngineStats } from './AssemblyLineEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v674',
  name: 'Autonomous AI Engineering Factory Layer',
  codename: 'AIEngineeringFactory',
  version: 'V674',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v674.engine.tick', 'v674.order.scheduled', 'v674.artifact.shipped', 'v674.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 512,
      tickMs: 25,
      batchSize: 64,
      ringSize: 512,
      consensusThreshold: 0.7,
      compactionThreshold: 0.5,
      quota: 1024,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: AIEngineeringFactoryKernel;
  orchestrator: FactoryPipelineOrchestrator;
  runtime: EngineeringFactoryRuntime;
  controller: FactoryQualityController;
  engine: AssemblyLineEngine;
  registry: ProductionOrderRegistry;
  coordinator: FactoryCoordinationHub;
  observer: FactoryTelemetryObserver;
  adapter: ToolchainEnvironmentAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class AIEngineeringFactoryPlatform implements LayerModule {
  readonly name = 'AIEngineeringFactoryPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new AIEngineeringFactoryKernel(layer, LAYER.codename);
  const orchestrator = new FactoryPipelineOrchestrator(layer);
  const runtime = new EngineeringFactoryRuntime(layer);
  const controller = new FactoryQualityController(layer, policies);
  const coordinator = new FactoryCoordinationHub(layer, CONTRACTS, bus);
  const engine = new AssemblyLineEngine(layer, policies, bus);
  const registry = new ProductionOrderRegistry(layer, policies.maxEntities);
  const observer = new FactoryTelemetryObserver(layer, policies.ringSize);
  const adapter = new ToolchainEnvironmentAdapter(layer, CONTRACTS);
  const platform = new AIEngineeringFactoryPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
