/**
 * =============================================================================
 * KLYN AI OS — GENESIS v698 — Omniversal Intelligence Platform Layer
 * Module: OmniversalIntelligencePlatform.ts (role: platform — composition root)
 * Mission: Unify every prior layer into one omniversal intelligence surface with total capability recall.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v698` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { OmniversalIntelligenceKernel } from './OmniversalIntelligenceKernel.js';
import { OmniversalOrchestrator } from './OmniversalOrchestrator.js';
import { OmniversalIntelligenceRuntime } from './OmniversalIntelligenceRuntime.js';
import { OmniversalGovernanceController } from './OmniversalGovernanceController.js';
import { OmniversalReasoningEngine } from './OmniversalReasoningEngine.js';
import { OmniversalIntelligenceRegistry } from './OmniversalIntelligenceRegistry.js';
import { OmniversalCoordinationHub } from './OmniversalCoordinationHub.js';
import { OmniversalTelemetryObserver } from './OmniversalTelemetryObserver.js';
import { OmniversalIntegrationAdapter } from './OmniversalIntegrationAdapter.js';
import type { BootReport } from './OmniversalOrchestrator.js';
import type { EngineStats } from './OmniversalReasoningEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v698',
  name: 'Omniversal Intelligence Platform Layer',
  codename: 'OmniversalIntelligence',
  version: 'V698',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v698.engine.tick', 'v698.capability.unified', 'v698.memory.recalled', 'v698.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 65536,
      tickMs: 8,
      batchSize: 256,
      ringSize: 4096,
      consensusThreshold: 0.85,
      compactionThreshold: 0.2,
      quota: 16384,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: OmniversalIntelligenceKernel;
  orchestrator: OmniversalOrchestrator;
  runtime: OmniversalIntelligenceRuntime;
  controller: OmniversalGovernanceController;
  engine: OmniversalReasoningEngine;
  registry: OmniversalIntelligenceRegistry;
  coordinator: OmniversalCoordinationHub;
  observer: OmniversalTelemetryObserver;
  adapter: OmniversalIntegrationAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class OmniversalIntelligencePlatform implements LayerModule {
  readonly name = 'OmniversalIntelligencePlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new OmniversalIntelligenceKernel(layer, LAYER.codename);
  const orchestrator = new OmniversalOrchestrator(layer);
  const runtime = new OmniversalIntelligenceRuntime(layer);
  const controller = new OmniversalGovernanceController(layer, policies);
  const coordinator = new OmniversalCoordinationHub(layer, CONTRACTS, bus);
  const engine = new OmniversalReasoningEngine(layer, policies, bus);
  const registry = new OmniversalIntelligenceRegistry(layer, policies.maxEntities);
  const observer = new OmniversalTelemetryObserver(layer, policies.ringSize);
  const adapter = new OmniversalIntegrationAdapter(layer, CONTRACTS);
  const platform = new OmniversalIntelligencePlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
