/**
 * =============================================================================
 * KLYN AI OS — GENESIS v681 — Autonomous DevOps Civilization Layer
 * Module: AutonomousDevOpsPlatform.ts (role: platform — composition root)
 * Mission: A civilization of pipelines that plan, verify, release, and heal deployments end to end.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v681` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { AutonomousDevOpsKernel } from './AutonomousDevOpsKernel.js';
import { DevOpsPipelineOrchestrator } from './DevOpsPipelineOrchestrator.js';
import { AutonomousDevOpsRuntime } from './AutonomousDevOpsRuntime.js';
import { DevOpsGovernanceController } from './DevOpsGovernanceController.js';
import { ContinuousDeliveryEngine } from './ContinuousDeliveryEngine.js';
import { ReleaseStateRegistry } from './ReleaseStateRegistry.js';
import { DevOpsCoordinationHub } from './DevOpsCoordinationHub.js';
import { DevOpsTelemetryObserver } from './DevOpsTelemetryObserver.js';
import { InfrastructureEnvironmentAdapter } from './InfrastructureEnvironmentAdapter.js';
import type { BootReport } from './DevOpsPipelineOrchestrator.js';
import type { EngineStats } from './ContinuousDeliveryEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v681',
  name: 'Autonomous DevOps Civilization Layer',
  codename: 'AutonomousDevOps',
  version: 'V681',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v681.engine.tick', 'v681.pipeline.run', 'v681.release.promoted', 'v681.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 1024,
      tickMs: 25,
      batchSize: 64,
      ringSize: 512,
      consensusThreshold: 0.8,
      compactionThreshold: 0.5,
      quota: 1024,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: AutonomousDevOpsKernel;
  orchestrator: DevOpsPipelineOrchestrator;
  runtime: AutonomousDevOpsRuntime;
  controller: DevOpsGovernanceController;
  engine: ContinuousDeliveryEngine;
  registry: ReleaseStateRegistry;
  coordinator: DevOpsCoordinationHub;
  observer: DevOpsTelemetryObserver;
  adapter: InfrastructureEnvironmentAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class AutonomousDevOpsPlatform implements LayerModule {
  readonly name = 'AutonomousDevOpsPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new AutonomousDevOpsKernel(layer, LAYER.codename);
  const orchestrator = new DevOpsPipelineOrchestrator(layer);
  const runtime = new AutonomousDevOpsRuntime(layer);
  const controller = new DevOpsGovernanceController(layer, policies);
  const coordinator = new DevOpsCoordinationHub(layer, CONTRACTS, bus);
  const engine = new ContinuousDeliveryEngine(layer, policies, bus);
  const registry = new ReleaseStateRegistry(layer, policies.maxEntities);
  const observer = new DevOpsTelemetryObserver(layer, policies.ringSize);
  const adapter = new InfrastructureEnvironmentAdapter(layer, CONTRACTS);
  const platform = new AutonomousDevOpsPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
