/**
 * =============================================================================
 * KLYN AI OS — GENESIS v675 — Multi-Agent Enterprise Operating System Layer
 * Module: MultiAgentEnterprisePlatform.ts (role: platform — composition root)
 * Mission: Coordinate fleets of specialist agents as a single enterprise operating system with governed autonomy.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v675` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { MultiAgentEnterpriseKernel } from './MultiAgentEnterpriseKernel.js';
import { AgentFleetOrchestrator } from './AgentFleetOrchestrator.js';
import { MultiAgentRuntime } from './MultiAgentRuntime.js';
import { AgentGovernanceController } from './AgentGovernanceController.js';
import { AgentSchedulerEngine } from './AgentSchedulerEngine.js';
import { AgentIdentityRegistry } from './AgentIdentityRegistry.js';
import { AgentCoordinationHub } from './AgentCoordinationHub.js';
import { AgentTelemetryObserver } from './AgentTelemetryObserver.js';
import { AgentEnvironmentAdapter } from './AgentEnvironmentAdapter.js';
import type { BootReport } from './AgentFleetOrchestrator.js';
import type { EngineStats } from './AgentSchedulerEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v675',
  name: 'Multi-Agent Enterprise Operating System Layer',
  codename: 'MultiAgentEnterprise',
  version: 'V675',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v675.engine.tick', 'v675.agent.spawned', 'v675.agent.completed', 'v675.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 4096,
      tickMs: 20,
      batchSize: 96,
      ringSize: 1024,
      consensusThreshold: 0.66,
      compactionThreshold: 0.45,
      quota: 2048,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: MultiAgentEnterpriseKernel;
  orchestrator: AgentFleetOrchestrator;
  runtime: MultiAgentRuntime;
  controller: AgentGovernanceController;
  engine: AgentSchedulerEngine;
  registry: AgentIdentityRegistry;
  coordinator: AgentCoordinationHub;
  observer: AgentTelemetryObserver;
  adapter: AgentEnvironmentAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class MultiAgentEnterprisePlatform implements LayerModule {
  readonly name = 'MultiAgentEnterprisePlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new MultiAgentEnterpriseKernel(layer, LAYER.codename);
  const orchestrator = new AgentFleetOrchestrator(layer);
  const runtime = new MultiAgentRuntime(layer);
  const controller = new AgentGovernanceController(layer, policies);
  const coordinator = new AgentCoordinationHub(layer, CONTRACTS, bus);
  const engine = new AgentSchedulerEngine(layer, policies, bus);
  const registry = new AgentIdentityRegistry(layer, policies.maxEntities);
  const observer = new AgentTelemetryObserver(layer, policies.ringSize);
  const adapter = new AgentEnvironmentAdapter(layer, CONTRACTS);
  const platform = new MultiAgentEnterprisePlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
