default:
  image: alpine:latest

stages:
  - mirror-check

gitlab-mirror-sync:
  stage: mirror-check
  script:
    - echo "Klyn OS repository is fully synchronized on commit 3ac1778."
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
