services:
  - type: web
    name: klyn-ai-os
    env: docker
    repo: https://github.com/usmanmuhd958-oss/klyn-ai
    region: frankfurt
    plan: free
    healthCheckPath: /status
    envVars:
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        value: ***REMOVED***
      - key: ADMIN_PASSWORD
        value: klyn
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
    dockerfilePath: ./Dockerfile
    autoDeploy: true
