/**
 * =============================================================================
 * KLYN AI OS — GENESIS v673 — KLYN Self-Evolving Operating System Layer
 * Module: AdaptiveMutationEngine.ts (role: engine)
 * Mission: An operating system that mutates its own modules through governed evolution cycles.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v673` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, monotonic } from '../platform/modules.js';
import type { LayerModule, ResolvedPolicies } from '../platform/modules.js';

export type EngineTask = () => void | Promise<void>;

export interface EngineStats {
  processed: number;
  errors: number;
  totalMs: number;
  lastTickMs: number;
  queueDepth: number;
}

export class AdaptiveMutationEngine implements LayerModule {
  readonly name = 'AdaptiveMutationEngine';
  readonly role = 'engine';
  readonly layer: string;
  readonly #policies: ResolvedPolicies;
  readonly #bus: EventBus;
  readonly #queue: EngineTask[] = [];
  readonly #log: Logger;
  #processed = 0;
  #errors = 0;
  #totalMs = 0;
  #lastTickMs = 0;
  #timer: ReturnType<typeof setInterval> | null = null;

  constructor(layer: string, policies: ResolvedPolicies, bus: EventBus, quiet = false) {
    this.layer = layer;
    this.#policies = policies;
    this.#bus = bus;
    this.#log = new Logger(layer + ':' + this.role, quiet ? 3 : 1);
  }

  start(): void {
    if (this.#timer) return;
    this.#timer = setInterval(() => {
      void this.tick();
    }, Math.max(5, this.#policies.tickMs));
    if (this.#timer.unref) this.#timer.unref();
  }

  stop(): void {
    if (this.#timer) {
      clearInterval(this.#timer);
      this.#timer = null;
    }
  }

  enqueue(task: EngineTask): void {
    this.#queue.push(task);
    this.#bus.emit(this.layer + '.engine.enqueued', { depth: this.#queue.length });
  }

  get depth(): number {
    return this.#queue.length;
  }

  async tick(batch = this.#policies.batchSize): Promise<number> {
    const startedAt = monotonic();
    let done = 0;
    while (done < batch) {
      const task = this.#queue.shift();
      if (!task) break;
      try {
        await task();
        this.#processed += 1;
      } catch {
        this.#errors += 1;
      }
      done += 1;
    }
    this.#lastTickMs = Math.round((monotonic() - startedAt) * 100) / 100;
    this.#totalMs += this.#lastTickMs;
    if (done > 0) {
      this.#bus.emit(this.layer + '.engine.tick', { processed: done, errors: this.#errors });
    }
    return done;
  }

  stats(): EngineStats {
    return {
      processed: this.#processed,
      errors: this.#errors,
      totalMs: Math.round(this.#totalMs * 100) / 100,
      lastTickMs: this.#lastTickMs,
      queueDepth: this.#queue.length,
    };
  }
}
