/**
 * =============================================================================
 * KLYN AI OS — GENESIS v673 — KLYN Self-Evolving Operating System Layer
 * Module: SelfEvolvingOSPlatform.ts (role: platform — composition root)
 * Mission: An operating system that mutates its own modules through governed evolution cycles.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v673` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { SelfEvolvingOSKernel } from './SelfEvolvingOSKernel.js';
import { EvolutionaryOSOrchestrator } from './EvolutionaryOSOrchestrator.js';
import { SelfEvolvingRuntime } from './SelfEvolvingRuntime.js';
import { EvolutionGovernanceController } from './EvolutionGovernanceController.js';
import { AdaptiveMutationEngine } from './AdaptiveMutationEngine.js';
import { EvolutionStateRegistry } from './EvolutionStateRegistry.js';
import { EvolutionaryCoordinationHub } from './EvolutionaryCoordinationHub.js';
import { EvolutionTelemetryObserver } from './EvolutionTelemetryObserver.js';
import { HostEnvironmentAdapter } from './HostEnvironmentAdapter.js';
import type { BootReport } from './EvolutionaryOSOrchestrator.js';
import type { EngineStats } from './AdaptiveMutationEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v673',
  name: 'KLYN Self-Evolving Operating System Layer',
  codename: 'SelfEvolvingOS',
  version: 'V673',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v673.engine.tick', 'v673.mutation.proposed', 'v673.mutation.applied', 'v673.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 8192,
      tickMs: 16,
      batchSize: 128,
      ringSize: 1024,
      consensusThreshold: 0.7,
      compactionThreshold: 0.3,
      quota: 4096,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: SelfEvolvingOSKernel;
  orchestrator: EvolutionaryOSOrchestrator;
  runtime: SelfEvolvingRuntime;
  controller: EvolutionGovernanceController;
  engine: AdaptiveMutationEngine;
  registry: EvolutionStateRegistry;
  coordinator: EvolutionaryCoordinationHub;
  observer: EvolutionTelemetryObserver;
  adapter: HostEnvironmentAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class SelfEvolvingOSPlatform implements LayerModule {
  readonly name = 'SelfEvolvingOSPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new SelfEvolvingOSKernel(layer, LAYER.codename);
  const orchestrator = new EvolutionaryOSOrchestrator(layer);
  const runtime = new SelfEvolvingRuntime(layer);
  const controller = new EvolutionGovernanceController(layer, policies);
  const coordinator = new EvolutionaryCoordinationHub(layer, CONTRACTS, bus);
  const engine = new AdaptiveMutationEngine(layer, policies, bus);
  const registry = new EvolutionStateRegistry(layer, policies.maxEntities);
  const observer = new EvolutionTelemetryObserver(layer, policies.ringSize);
  const adapter = new HostEnvironmentAdapter(layer, CONTRACTS);
  const platform = new SelfEvolvingOSPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
