/**
 * =============================================================================
 * KLYN AI OS — GENESIS v687 — AI Organization Operating System Layer
 * Module: AIOrganizationOSPlatform.ts (role: platform — composition root)
 * Mission: Run organizations as programmable systems: roles, missions, and workflows as first-class objects.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v687` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { AIOrganizationOSKernel } from './AIOrganizationOSKernel.js';
import { OrganizationStructureOrchestrator } from './OrganizationStructureOrchestrator.js';
import { AIOrganizationRuntime } from './AIOrganizationRuntime.js';
import { OrganizationGovernanceController } from './OrganizationGovernanceController.js';
import { OrgWorkflowEngine } from './OrgWorkflowEngine.js';
import { OrganizationRoleRegistry } from './OrganizationRoleRegistry.js';
import { OrganizationCoordinationHub } from './OrganizationCoordinationHub.js';
import { OrganizationTelemetryObserver } from './OrganizationTelemetryObserver.js';
import { OrgSystemAdapter } from './OrgSystemAdapter.js';
import type { BootReport } from './OrganizationStructureOrchestrator.js';
import type { EngineStats } from './OrgWorkflowEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v687',
  name: 'AI Organization Operating System Layer',
  codename: 'AIOrganizationOS',
  version: 'V687',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v687.engine.tick', 'v687.role.assigned', 'v687.mission.completed', 'v687.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 4096,
      tickMs: 25,
      batchSize: 64,
      ringSize: 512,
      consensusThreshold: 0.66,
      compactionThreshold: 0.5,
      quota: 2048,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: AIOrganizationOSKernel;
  orchestrator: OrganizationStructureOrchestrator;
  runtime: AIOrganizationRuntime;
  controller: OrganizationGovernanceController;
  engine: OrgWorkflowEngine;
  registry: OrganizationRoleRegistry;
  coordinator: OrganizationCoordinationHub;
  observer: OrganizationTelemetryObserver;
  adapter: OrgSystemAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class AIOrganizationOSPlatform implements LayerModule {
  readonly name = 'AIOrganizationOSPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new AIOrganizationOSKernel(layer, LAYER.codename);
  const orchestrator = new OrganizationStructureOrchestrator(layer);
  const runtime = new AIOrganizationRuntime(layer);
  const controller = new OrganizationGovernanceController(layer, policies);
  const coordinator = new OrganizationCoordinationHub(layer, CONTRACTS, bus);
  const engine = new OrgWorkflowEngine(layer, policies, bus);
  const registry = new OrganizationRoleRegistry(layer, policies.maxEntities);
  const observer = new OrganizationTelemetryObserver(layer, policies.ringSize);
  const adapter = new OrgSystemAdapter(layer, CONTRACTS);
  const platform = new AIOrganizationOSPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
