// =============================================================================
// KLYN AI OS — self-healing-runtime — Synthetic Mutation & Quality Gate Harness
// File: packages/self-healing-runtime/src/mutation_harness.ts
//
// Autonomous testing surface for newly generated backend routes:
//   - synthesizeEdgeCaseMutations(): deterministic synthetic mutations that
//     probe malformed input handling (empty body, invalid JSON, oversized
//     payload, wrong types, unknown fields, wrong content-type).
//   - generatePropertyTests(): a vitest source file encoding route
//     invariants (status-code classes, no crashes on malformed input,
//     bounded latency budget, idempotent GETs).
//   - QualityGate: auto-rejects an AI-generated patch that drops test
//     coverage or introduces unhandled promise rejections.
// =============================================================================
import { InlinePatchValidator } from './patch_validator.js';

export interface BackendRoute {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  path: string;
  handlerName: string;
  /** Optional field → expected type ('string' | 'number' | 'boolean' | 'object' | 'array'). */
  bodySchema?: Record<string, string>;
}

export interface EdgeCaseMutation {
  name: string;
  /** JSON body to send (already stringified where relevant). */
  body: string | null;
  /** JS expression that builds the body at TEST RUNTIME (keeps generated
   *  test source small — oversized payloads are not inlined). */
  bodyExpr?: string;
  /** Expected HTTP status class (e.g. 4xx for client errors). */
  expectStatus: number;
}

export interface GateVerdict {
  approved: boolean;
  reasons: string[];
}

const VALID_TYPES = new Set(['string', 'number', 'boolean', 'object', 'array']);

/** Deterministic synthetic edge-case mutations for a backend route. */
export function synthesizeEdgeCaseMutations(route: BackendRoute): EdgeCaseMutation[] {
  const cases: EdgeCaseMutation[] = [
    { name: 'empty body', body: '', expectStatus: 400 },
    { name: 'malformed JSON', body: '{"id": ', expectStatus: 400 },
    { name: 'null body', body: 'null', expectStatus: 400 },
    { name: 'array where object expected', body: '[]', expectStatus: 400 },
    { name: 'unknown top-level fields', body: JSON.stringify({ __klyn_synthetic: 'surprise', extra: 1 }), expectStatus: 400 },
    {
      name: 'oversized payload',
      body: JSON.stringify({ blob: 'x'.repeat(2 * 1024 * 1024) }),
      bodyExpr: "JSON.stringify({ blob: 'x'.repeat(2 * 1024 * 1024) })",
      expectStatus: 413,
    },
  ];

  const schema = route.bodySchema ?? {};
  for (const [field, type] of Object.entries(schema)) {
    if (!VALID_TYPES.has(type)) continue;
    const wrong: Record<string, unknown> = {};
    // Provide one valid value for every other field so the mutation is
    // isolated to this single field.
    for (const [otherField, otherType] of Object.entries(schema)) {
      if (otherField !== field) wrong[otherField] = sampleValue(otherType);
    }
    wrong[field] = wrongValue(type);
    cases.push({ name: `wrong type for ${field} (expected ${type})`, body: JSON.stringify(wrong), expectStatus: 400 });
  }

  return cases;
}

function sampleValue(type: string): unknown {
  switch (type) {
    case 'string': return 'sample';
    case 'number': return 42;
    case 'boolean': return true;
    case 'array': return [];
    case 'object': return {};
    default: return null;
  }
}

function wrongValue(type: string): unknown {
  switch (type) {
    case 'string': return { nested: 'object instead of string' };
    case 'number': return 'not-a-number';
    case 'boolean': return 'not-a-boolean';
    case 'array': return { not: 'an array' };
    case 'object': return [1, 2, 3];
    default: return null;
  }
}

/**
 * Generate a property-based vitest suite for a backend route. The generated
 * source is deterministic for a given route (stable across runs) so it can be
 * persisted and executed by the CI test runner.
 */
export function generatePropertyTests(route: BackendRoute): string {
  const suiteName = `${route.method} ${route.path}`.replace(/[^A-Za-z0-9 ]/g, ' ').trim();
  const mutations = synthesizeEdgeCaseMutations(route);
  const mutationCases = mutations
    .map(
      (m) => `  it('rejects "${m.name}" with a ${m.expectStatus}-class status', async () => {
    const res = await handler(${m.bodyExpr ?? JSON.stringify(m.body)}, {});
    expect(res.status).toBeGreaterThanOrEqual(${Math.floor(m.expectStatus / 100) * 100});
    expect(res.status).toBeLessThan(${Math.floor(m.expectStatus / 100) * 100 + 100});
  });`
    )
    .join('\n');

  return `// Auto-generated by Klyn AI OS quality-gate harness (deterministic).
// Route: ${route.method} ${route.path} (handler: ${route.handlerName})
import { describe, it, expect } from 'vitest';

// The handler under test must satisfy the documented shape:
//   (body: unknown, ctx: Record<string, unknown>) => Promise<{ status: number; body?: unknown }>
const handler = (${route.handlerName} as unknown) as (
  body: unknown,
  ctx: Record<string, unknown>
) => Promise<{ status: number; body?: unknown }>;

describe('${suiteName} — property suite', () => {
${mutationCases}

  it('never throws on malformed input (no unhandled rejection)', async () => {
    await expect(handler(null, {})).resolves.toBeDefined();
    await expect(handler('{bad json', {})).resolves.toBeDefined();
  });

  it('responds within the latency budget', async () => {
    const t0 = performance.now();
    await handler({}, {});
    expect(performance.now() - t0).toBeLessThan(1000);
  });
});
`;
}

export class QualityGate {
  constructor(private validator: InlinePatchValidator = new InlinePatchValidator()) {}

  /**
   * Evaluate a candidate patch against the Phase 3 quality gates:
   *   1. syntax + structural validity
   *   2. no unhandled promise rejections
   *   3. test coverage must not drop below baseline
   * Any failed gate → `approved: false` with the reasons.
   */
  evaluate(input: { code: string; coverageBefore?: number; coverageAfter?: number }): GateVerdict {
    const reasons: string[] = [];

    const report = this.validator.validate(input.code);
    if (!report.valid) {
      reasons.push(`Syntax/structural gate failed: ${report.errors.join('; ')}`);
    }

    const rejections = report.warnings.filter((w) => w.startsWith('Unhandled promise rejection'));
    if (rejections.length > 0) {
      reasons.push(`Unhandled-promise-rejection gate failed: ${rejections[0]}`);
    }

    if (
      input.coverageBefore !== undefined &&
      input.coverageAfter !== undefined &&
      input.coverageAfter < input.coverageBefore - 1e-9
    ) {
      reasons.push(
        `Coverage gate failed: ${(input.coverageBefore * 100).toFixed(1)}% → ${(input.coverageAfter * 100).toFixed(1)}%`
      );
    }

    return { approved: reasons.length === 0, reasons };
  }

  /** Shorthand for the rejection gate only (used by the mutation loop). */
  hasUnhandledRejections(code: string): boolean {
    return this.validator.validate(code).warnings.some((w) => w.startsWith('Unhandled promise rejection'));
  }
}

export default QualityGate;
