import { createHash } from "node:crypto";

export type AgentTaskStatus = "pending" | "running" | "succeeded" | "failed" | "rolled_back" | "cancelled" | "blocked";
export interface AgentTaskContext { readonly taskId:string; readonly agentId:string; readonly input:unknown; readonly outputs:Readonly<Record<string,unknown>>; readonly idempotencyKey:string; readonly signal:AbortSignal; }
export interface AgentTask { readonly id:string; readonly agentId:string; readonly input:unknown; readonly dependsOn?:readonly string[]; readonly run:(context:AgentTaskContext, signal?:AbortSignal)=>Promise<unknown>; readonly rollback?:(context:AgentTaskContext,error:unknown)=>Promise<void>; }
export interface DagSnapshot { readonly statuses:Readonly<Record<string,AgentTaskStatus>>; readonly outputs:Readonly<Record<string,unknown>>; readonly errors:Readonly<Record<string,string>>; readonly idempotencyKeys:Readonly<Record<string,string>>; }
export interface DagExecutionOptions { readonly maxConcurrency?:number; readonly failFast?:boolean; readonly timeoutMs?:number; readonly signal?:AbortSignal; }
export class DagValidationError extends Error { constructor(message:string){super(message);this.name="DagValidationError";} }
export class DagCancelledError extends Error { constructor(message="DAG execution cancelled"){super(message);this.name="DagCancelledError";} }
export class DagTimeoutError extends Error { constructor(taskId:string,ms:number){super(`Task ${taskId} timed out after ${ms}ms`);this.name="DagTimeoutError";} }
export function deterministicIdempotencyKey(task:Pick<AgentTask,"id"|"agentId"|"input"|"dependsOn">):string { return createHash("sha256").update(JSON.stringify({id:task.id,agentId:task.agentId,input:task.input,dependsOn:[...(task.dependsOn??[])].sort()})).digest("hex"); }
export class SwarmDagOrchestrator {
 private readonly tasks=new Map<string,AgentTask>();
 addTask(task:AgentTask):this{if(this.tasks.has(task.id))throw new DagValidationError(`Duplicate task id: ${task.id}`);this.tasks.set(task.id,task);return this;}
 addTasks(tasks:readonly AgentTask[]):this{for(const t of tasks)this.addTask(t);return this;}
 validate():void{this.validateDependenciesOnly();this.topologicalSort();}
 topologicalSort():string[][]{this.validateDependenciesOnly();const indegree=new Map<string,number>(),out=new Map<string,string[]>();for(const id of this.tasks.keys()){indegree.set(id,0);out.set(id,[]);}for(const t of this.tasks.values())for(const d of t.dependsOn??[]){indegree.set(t.id,indegree.get(t.id)!+1);out.get(d)!.push(t.id);}const layers:string[][]=[];let ready=[...this.tasks.keys()].filter(id=>indegree.get(id)===0),visited=0;while(ready.length){const layer=[...ready].sort();layers.push(layer);visited+=layer.length;const next:string[]=[];for(const id of layer)for(const child of out.get(id)!){const n=indegree.get(child)!-1;indegree.set(child,n);if(n===0)next.push(child);}ready=next;}if(visited!==this.tasks.size)throw new DagValidationError("DAG contains a cycle");return layers;}
 async execute(options:DagExecutionOptions={}):Promise<DagSnapshot>{this.validate();const limit=Number.isFinite(options.maxConcurrency)?Math.max(1,Math.floor(options.maxConcurrency!)):Number.MAX_SAFE_INTEGER;const statuses:Record<string,AgentTaskStatus>={},outputs:Record<string,unknown>={},errors:Record<string,string>={},idempotencyKeys:Record<string,string>={};for(const t of this.tasks.values()){statuses[t.id]="pending";idempotencyKeys[t.id]=deterministicIdempotencyKey(t);}const done:string[]=[],controller=new AbortController();const abort=()=>controller.abort(options.signal?.reason??new DagCancelledError());if(options.signal?.aborted)abort();else options.signal?.addEventListener("abort",abort,{once:true});const ctx=(t:AgentTask):AgentTaskContext=>({taskId:t.id,agentId:t.agentId,input:t.input,outputs:{...outputs},idempotencyKey:idempotencyKeys[t.id],signal:controller.signal});try{for(const layer of this.topologicalSort())for(let i=0;i<layer.length;i+=limit){if(controller.signal.aborted)throw new DagCancelledError();const batch=layer.slice(i,i+limit);const results=await Promise.all(batch.map(async id=>{const t=this.tasks.get(id)!;if((t.dependsOn??[]).some(d=>statuses[d]!=="succeeded")){statuses[id]="blocked";errors[id]="dependency did not succeed";return{id,ok:false as const,error:new Error(errors[id])};}statuses[id]="running";try{outputs[id]=await this.run(t,ctx(t),options.timeoutMs,controller.signal);statuses[id]="succeeded";done.push(id);return{id,ok:true as const};}catch(error){statuses[id]=controller.signal.aborted?"cancelled":"failed";errors[id]=error instanceof Error?error.message:String(error);if(options.failFast??true)controller.abort(error);return{id,ok:false as const,error};}}));const failure=results.find(r=>!r.ok);if(failure&&(options.failFast??true))throw failure.error;}}catch(error){await this.rollback(done,statuses,outputs,errors,error,controller.signal);throw error;}finally{options.signal?.removeEventListener("abort",abort);}return{statuses:{...statuses},outputs:{...outputs},errors:{...errors},idempotencyKeys:{...idempotencyKeys}};}
 private async run(t:AgentTask,c:AgentTaskContext,ms:number|undefined,s:AbortSignal):Promise<unknown>{if(!ms||ms<=0)return t.run(c,s);return new Promise((resolve,reject)=>{let settled=false;const timer=setTimeout(()=>{if(settled)return;settled=true;reject(new DagTimeoutError(t.id,ms));},ms);const onAbort=()=>{if(settled)return;settled=true;clearTimeout(timer);reject(new DagCancelledError());};s.addEventListener("abort",onAbort,{once:true});t.run(c,s).then(v=>{if(!settled){settled=true;clearTimeout(timer);s.removeEventListener("abort",onAbort);resolve(v);}},e=>{if(!settled){settled=true;clearTimeout(timer);s.removeEventListener("abort",onAbort);reject(e);}});});}
 private async rollback(done:readonly string[],statuses:Record<string,AgentTaskStatus>,outputs:Record<string,unknown>,errors:Record<string,string>,cause:unknown,signal:AbortSignal){for(const id of [...done].reverse()){const t=this.tasks.get(id)!;if(!t.rollback)continue;try{await t.rollback({taskId:t.id,agentId:t.agentId,input:t.input,outputs:{...outputs},idempotencyKey:deterministicIdempotencyKey(t),signal},cause);statuses[id]="rolled_back";delete outputs[id];}catch(e){errors[`${id}:rollback`]=e instanceof Error?e.message:String(e);}}}
 private validateDependenciesOnly(){for(const t of this.tasks.values())for(const d of t.dependsOn??[])if(!this.tasks.has(d))throw new DagValidationError(`Unknown dependency ${d} for task ${t.id}`);}
}
