/**
 * =============================================================================
 * KLYN AI OS — GENESIS v685 — Synthetic Intelligence Architecture Layer
 * Module: smoke.ts (role: self-test harness)
 * Mission: Compose synthetic cognition from modular inference units bound by governed architectures.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v685` to regenerate.
 * =============================================================================
 */

import { createLayer, LAYER, CONTRACTS } from './SyntheticIntelligencePlatform.js';

interface CheckState {
  checks: number;
  failures: number;
}

const state: CheckState = { checks: 0, failures: 0 };

function check(name: string, ok: boolean, detail = ''): void {
  state.checks += 1;
  if (ok) {
    console.log('  [PASS] ' + name);
  } else {
    state.failures += 1;
    console.error('  [FAIL] ' + name + (detail ? '  -> ' + detail : ''));
  }
}

async function main(): Promise<void> {
  const startedAt = Date.now();
  console.log('GENESIS ' + LAYER.id + ' smoke — ' + LAYER.name);

  check('layer manifest identity', LAYER.id === 'v685' && LAYER.codename === 'SyntheticIntelligence', JSON.stringify(LAYER));
  check('layer exposes 4 contracts', CONTRACTS.length === 4, 'contracts=' + CONTRACTS.length);

  const handle = createLayer({ maxEntities: 8, tickMs: 60000, batchSize: 8, ringSize: 16, quota: 8 });

  check('kernel registers exactly 10 modules', handle.kernel.size === 10, 'size=' + handle.kernel.size);

  const report = await handle.start();
  check('orchestrator boots with zero failures', report.failures.length === 0, report.failures.join(','));
  check('kernel health is ready', handle.kernel.health().ready, JSON.stringify(handle.kernel.health()));
  check('runtime reaches running state', handle.runtime.state === 'running', 'state=' + handle.runtime.state);

  const admitted = handle.controller.admit('smoke');
  check('controller admits in-quota scope', admitted.allowed, admitted.reason);

  let rejected = false;
  for (let i = 0; i < 64; i += 1) {
    if (!handle.controller.admit('smoke').allowed) { rejected = true; break; }
  }
  check('controller rejects over-quota scope', rejected);

  let sawTick = false;
  handle.coordinator.on('v685.engine.tick', () => { sawTick = true; });

  handle.engine.enqueue(() => { handle.observer.record('work', 1); });
  const done = await handle.engine.tick(8);
  check('engine processes queued work', done >= 1 && handle.engine.stats().errors === 0, 'done=' + done);
  check('engine tick event reaches coordinator', sawTick);
  check('observer records metric', handle.observer.count('work') >= 1, 'count=' + handle.observer.count('work'));

  for (let i = 0; i < 10; i += 1) handle.registry.set('entity-' + i, i);
  const registry = handle.registry.stats();
  check('registry enforces LRU capacity', registry.size === 8 && registry.evictions >= 2, 'size=' + registry.size + ' evictions=' + registry.evictions);

  check('adapter accepts contract boundary', handle.adapter.call('v685.engine.tick').accepted);
  check('adapter probe reports healthy environment', handle.adapter.probe().ok);

  await handle.stop();
  check('runtime drains to stopped', handle.runtime.state === 'stopped', 'state=' + handle.runtime.state);

  const elapsedMs = Date.now() - startedAt;
  const passed = state.checks - state.failures;
  const ok = state.failures === 0;
  console.log('LAYER ' + LAYER.id + ' ' + (ok ? 'PASS' : 'FAIL') + ' (' + passed + '/' + state.checks + ') in ' + elapsedMs + 'ms');
  if (!ok) process.exitCode = 1;
}

void main();
