/**
 * =============================================================================
 * KLYN AI OS — GENESIS v690 — Universal AI Operating Fabric Layer
 * Module: UniversalAIOperatingFabricPlatform.ts (role: platform — composition root)
 * Mission: A universal fabric weaving compute, memory, and intelligence into one coherent operating surface.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v690` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { AIOperatingFabricKernel } from './AIOperatingFabricKernel.js';
import { FabricWeaveOrchestrator } from './FabricWeaveOrchestrator.js';
import { AIOperatingFabricRuntime } from './AIOperatingFabricRuntime.js';
import { FabricGovernanceController } from './FabricGovernanceController.js';
import { FabricExecutionEngine } from './FabricExecutionEngine.js';
import { FabricResourceRegistry } from './FabricResourceRegistry.js';
import { FabricCoordinationHub } from './FabricCoordinationHub.js';
import { FabricTelemetryObserver } from './FabricTelemetryObserver.js';
import { FabricHostAdapter } from './FabricHostAdapter.js';
import type { BootReport } from './FabricWeaveOrchestrator.js';
import type { EngineStats } from './FabricExecutionEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v690',
  name: 'Universal AI Operating Fabric Layer',
  codename: 'AIOperatingFabric',
  version: 'V690',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v690.engine.tick', 'v690.thread.woven', 'v690.fabric.repaired', 'v690.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 65536,
      tickMs: 8,
      batchSize: 256,
      ringSize: 2048,
      consensusThreshold: 0.7,
      compactionThreshold: 0.25,
      quota: 16384,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: AIOperatingFabricKernel;
  orchestrator: FabricWeaveOrchestrator;
  runtime: AIOperatingFabricRuntime;
  controller: FabricGovernanceController;
  engine: FabricExecutionEngine;
  registry: FabricResourceRegistry;
  coordinator: FabricCoordinationHub;
  observer: FabricTelemetryObserver;
  adapter: FabricHostAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class UniversalAIOperatingFabricPlatform implements LayerModule {
  readonly name = 'UniversalAIOperatingFabricPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new AIOperatingFabricKernel(layer, LAYER.codename);
  const orchestrator = new FabricWeaveOrchestrator(layer);
  const runtime = new AIOperatingFabricRuntime(layer);
  const controller = new FabricGovernanceController(layer, policies);
  const coordinator = new FabricCoordinationHub(layer, CONTRACTS, bus);
  const engine = new FabricExecutionEngine(layer, policies, bus);
  const registry = new FabricResourceRegistry(layer, policies.maxEntities);
  const observer = new FabricTelemetryObserver(layer, policies.ringSize);
  const adapter = new FabricHostAdapter(layer, CONTRACTS);
  const platform = new UniversalAIOperatingFabricPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
