/**
 * =============================================================================
 * KLYN AI OS — GENESIS v694 — Future Computing Architecture Layer
 * Module: FutureComputingPlatform.ts (role: platform — composition root)
 * Mission: Architect for post-von-Neumann substrates: quantum-classical fusion and heterogeneous compute.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v694` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { FutureComputingKernel } from './FutureComputingKernel.js';
import { FutureArchitectureOrchestrator } from './FutureArchitectureOrchestrator.js';
import { FutureComputingRuntime } from './FutureComputingRuntime.js';
import { FutureGovernanceController } from './FutureGovernanceController.js';
import { QuantumClassicalEngine } from './QuantumClassicalEngine.js';
import { FutureHardwareRegistry } from './FutureHardwareRegistry.js';
import { FutureComputingCoordinationHub } from './FutureComputingCoordinationHub.js';
import { FutureComputingTelemetryObserver } from './FutureComputingTelemetryObserver.js';
import { FutureHardwareAdapter } from './FutureHardwareAdapter.js';
import type { BootReport } from './FutureArchitectureOrchestrator.js';
import type { EngineStats } from './QuantumClassicalEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v694',
  name: 'Future Computing Architecture Layer',
  codename: 'FutureComputing',
  version: 'V694',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v694.engine.tick', 'v694.substrate.abstracted', 'v694.fusion.scheduled', 'v694.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 32768,
      tickMs: 8,
      batchSize: 256,
      ringSize: 2048,
      consensusThreshold: 0.9,
      compactionThreshold: 0.25,
      quota: 16384,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: FutureComputingKernel;
  orchestrator: FutureArchitectureOrchestrator;
  runtime: FutureComputingRuntime;
  controller: FutureGovernanceController;
  engine: QuantumClassicalEngine;
  registry: FutureHardwareRegistry;
  coordinator: FutureComputingCoordinationHub;
  observer: FutureComputingTelemetryObserver;
  adapter: FutureHardwareAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class FutureComputingPlatform implements LayerModule {
  readonly name = 'FutureComputingPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new FutureComputingKernel(layer, LAYER.codename);
  const orchestrator = new FutureArchitectureOrchestrator(layer);
  const runtime = new FutureComputingRuntime(layer);
  const controller = new FutureGovernanceController(layer, policies);
  const coordinator = new FutureComputingCoordinationHub(layer, CONTRACTS, bus);
  const engine = new QuantumClassicalEngine(layer, policies, bus);
  const registry = new FutureHardwareRegistry(layer, policies.maxEntities);
  const observer = new FutureComputingTelemetryObserver(layer, policies.ringSize);
  const adapter = new FutureHardwareAdapter(layer, CONTRACTS);
  const platform = new FutureComputingPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
