/**
 * =============================================================================
 * KLYN AI OS — GENESIS v697 — Recursive Enterprise Evolution Layer
 * Module: RecursiveEnterpriseEvolutionPlatform.ts (role: platform — composition root)
 * Mission: The enterprise that rewrites itself: each generation improves the mechanism that improves it.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v697` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { RecursiveEvolutionKernel } from './RecursiveEvolutionKernel.js';
import { RecursiveEvolutionOrchestrator } from './RecursiveEvolutionOrchestrator.js';
import { RecursiveEvolutionRuntime } from './RecursiveEvolutionRuntime.js';
import { RecursiveGovernanceController } from './RecursiveGovernanceController.js';
import { SelfImprovementEngine } from './SelfImprovementEngine.js';
import { EvolutionGenerationRegistry } from './EvolutionGenerationRegistry.js';
import { RecursiveCoordinationHub } from './RecursiveCoordinationHub.js';
import { RecursiveTelemetryObserver } from './RecursiveTelemetryObserver.js';
import { EvolutionEnvironmentAdapter } from './EvolutionEnvironmentAdapter.js';
import type { BootReport } from './RecursiveEvolutionOrchestrator.js';
import type { EngineStats } from './SelfImprovementEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v697',
  name: 'Recursive Enterprise Evolution Layer',
  codename: 'RecursiveEnterpriseEvolution',
  version: 'V697',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v697.engine.tick', 'v697.generation.evolved', 'v697.fitness.recorded', 'v697.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 4096,
      tickMs: 16,
      batchSize: 128,
      ringSize: 1024,
      consensusThreshold: 0.75,
      compactionThreshold: 0.35,
      quota: 4096,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: RecursiveEvolutionKernel;
  orchestrator: RecursiveEvolutionOrchestrator;
  runtime: RecursiveEvolutionRuntime;
  controller: RecursiveGovernanceController;
  engine: SelfImprovementEngine;
  registry: EvolutionGenerationRegistry;
  coordinator: RecursiveCoordinationHub;
  observer: RecursiveTelemetryObserver;
  adapter: EvolutionEnvironmentAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class RecursiveEnterpriseEvolutionPlatform implements LayerModule {
  readonly name = 'RecursiveEnterpriseEvolutionPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new RecursiveEvolutionKernel(layer, LAYER.codename);
  const orchestrator = new RecursiveEvolutionOrchestrator(layer);
  const runtime = new RecursiveEvolutionRuntime(layer);
  const controller = new RecursiveGovernanceController(layer, policies);
  const coordinator = new RecursiveCoordinationHub(layer, CONTRACTS, bus);
  const engine = new SelfImprovementEngine(layer, policies, bus);
  const registry = new EvolutionGenerationRegistry(layer, policies.maxEntities);
  const observer = new RecursiveTelemetryObserver(layer, policies.ringSize);
  const adapter = new EvolutionEnvironmentAdapter(layer, CONTRACTS);
  const platform = new RecursiveEnterpriseEvolutionPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
