/**
 * =============================================================================
 * KLYN AI OS — GENESIS v689 — Autonomous Enterprise Network Layer
 * Module: AutonomousEnterpriseNetworkPlatform.ts (role: platform — composition root)
 * Mission: A zero-configuration enterprise mesh where every service, agent, and human connects securely.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v689` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { EnterpriseNetworkKernel } from './EnterpriseNetworkKernel.js';
import { NetworkMeshOrchestrator } from './NetworkMeshOrchestrator.js';
import { EnterpriseNetworkRuntime } from './EnterpriseNetworkRuntime.js';
import { NetworkGovernanceController } from './NetworkGovernanceController.js';
import { NetworkRoutingEngine } from './NetworkRoutingEngine.js';
import { NetworkNodeRegistry } from './NetworkNodeRegistry.js';
import { NetworkCoordinationHub } from './NetworkCoordinationHub.js';
import { NetworkTelemetryObserver } from './NetworkTelemetryObserver.js';
import { EnterpriseProtocolAdapter } from './EnterpriseProtocolAdapter.js';
import type { BootReport } from './NetworkMeshOrchestrator.js';
import type { EngineStats } from './NetworkRoutingEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v689',
  name: 'Autonomous Enterprise Network Layer',
  codename: 'EnterpriseNetwork',
  version: 'V689',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v689.engine.tick', 'v689.node.attached', 'v689.route.recomputed', 'v689.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 32768,
      tickMs: 12,
      batchSize: 192,
      ringSize: 2048,
      consensusThreshold: 0.6,
      compactionThreshold: 0.3,
      quota: 8192,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: EnterpriseNetworkKernel;
  orchestrator: NetworkMeshOrchestrator;
  runtime: EnterpriseNetworkRuntime;
  controller: NetworkGovernanceController;
  engine: NetworkRoutingEngine;
  registry: NetworkNodeRegistry;
  coordinator: NetworkCoordinationHub;
  observer: NetworkTelemetryObserver;
  adapter: EnterpriseProtocolAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class AutonomousEnterpriseNetworkPlatform implements LayerModule {
  readonly name = 'AutonomousEnterpriseNetworkPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new EnterpriseNetworkKernel(layer, LAYER.codename);
  const orchestrator = new NetworkMeshOrchestrator(layer);
  const runtime = new EnterpriseNetworkRuntime(layer);
  const controller = new NetworkGovernanceController(layer, policies);
  const coordinator = new NetworkCoordinationHub(layer, CONTRACTS, bus);
  const engine = new NetworkRoutingEngine(layer, policies, bus);
  const registry = new NetworkNodeRegistry(layer, policies.maxEntities);
  const observer = new NetworkTelemetryObserver(layer, policies.ringSize);
  const adapter = new EnterpriseProtocolAdapter(layer, CONTRACTS);
  const platform = new AutonomousEnterpriseNetworkPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
