import { AgentConsensusEngine, type ConsensusVote } from "./consensus/AgentConsensusEngine.js";
export type ArbitrationDisposition="ACCEPT"|"REJECT"|"UNRESOLVED";
export interface ArbitrationVote<T=unknown>{readonly agentId:string;readonly role:"ARCHITECT"|"BUILDER"|"VALIDATOR"|"EVIDENCE";readonly state:T;readonly evidenceWeight:number;readonly epistemicState:"UNKNOWN"|"CLAIMED"|"OBSERVED"|"EVIDENCE-SUPPORTED"|"VERIFIED";}
export interface ArbitrationDecision<T=unknown>{readonly disposition:ArbitrationDisposition;readonly term:number;readonly revision:number;readonly quorum:number;readonly voters:readonly string[];readonly weightedSupport:number;readonly weightedOpposition:number;readonly winningState?:Readonly<T>;}
export interface ConsensusArbitratorPolicy{readonly minimumWeightedSupport:number;readonly minimumWeightedMargin:number;}
export const DEFAULT_ARBITRATION_POLICY:ConsensusArbitratorPolicy=Object.freeze({minimumWeightedSupport:0.6,minimumWeightedMargin:0.2});
export class ConsensusArbitrationError extends Error{readonly code="CONSENSUS_ARBITRATION_ERROR" as const;constructor(message:string){super(message);this.name="ConsensusArbitrationError";}}
interface WeightedGroup<T>{readonly key:string;readonly state:T;readonly weight:number;readonly voters:readonly string[];}
export class ConsensusArbitrator<T=unknown>{private readonly consensus:AgentConsensusEngine<T>;private readonly policy:ConsensusArbitratorPolicy;constructor(clusterSize:number,policy:ConsensusArbitratorPolicy=DEFAULT_ARBITRATION_POLICY){if(!Number.isInteger(clusterSize)||clusterSize<1)throw new ConsensusArbitrationError("clusterSize must be a positive integer");if(!Number.isFinite(policy.minimumWeightedSupport)||policy.minimumWeightedSupport<=0||policy.minimumWeightedSupport>1)throw new ConsensusArbitrationError("minimumWeightedSupport must be in (0, 1]");if(!Number.isFinite(policy.minimumWeightedMargin)||policy.minimumWeightedMargin<0||policy.minimumWeightedMargin>1)throw new ConsensusArbitrationError("minimumWeightedMargin must be in [0, 1]");this.consensus=new AgentConsensusEngine<T>(clusterSize);this.policy=policy;}
arbitrate(votes:readonly ArbitrationVote<T>[],term=1,revision=1):ArbitrationDecision<T>{this.validateVotes(votes);this.consensus.beginProposal({term,revision,state:votes[0].state});const groups=this.groupVotes(votes);const ranked=[...groups].sort((a,b)=>b.weight-a.weight||b.voters.length-a.voters.length||a.key.localeCompare(b.key));const winner=ranked[0];const runnerUp=ranked[1];const weightedSupport=winner?.weight??0;const weightedOpposition=Math.max(0,1-weightedSupport);const margin=weightedSupport-weightedOpposition;for(const vote of votes){const consensusVote:ConsensusVote<T>=Object.freeze({nodeId:vote.agentId,term,revision,state:vote.state});this.consensus.castVote(consensusVote);}const quorumDecision=this.consensus.decide();if(!winner||!quorumDecision)return Object.freeze({disposition:"UNRESOLVED",term,revision,quorum:0,voters:Object.freeze([]),weightedSupport,weightedOpposition});const splitBrain=runnerUp!==undefined&&Math.abs(winner.weight-runnerUp.weight)<this.policy.minimumWeightedMargin;const supported=weightedSupport>=this.policy.minimumWeightedSupport&&margin>=this.policy.minimumWeightedMargin;if(splitBrain||!supported)return Object.freeze({disposition:"REJECT",term,revision,quorum:quorumDecision.quorum,voters:Object.freeze([...quorumDecision.voters]),weightedSupport,weightedOpposition});if(!this.sameState(quorumDecision.state,winner.state))throw new ConsensusArbitrationError("Consensus engine decision diverged from weighted arbitration winner");return Object.freeze({disposition:"ACCEPT",term:quorumDecision.term,revision:quorumDecision.revision,quorum:quorumDecision.quorum,voters:Object.freeze([...quorumDecision.voters]),weightedSupport,weightedOpposition,winningState:quorumDecision.state});}
reset():void{this.consensus.reset();}
private validateVotes(votes:readonly ArbitrationVote<T>[]):void{if(votes.length===0)throw new ConsensusArbitrationError("At least one vote is required");const ids=new Set<string>();for(const vote of votes){if(!vote.agentId.trim())throw new ConsensusArbitrationError("Agent id must not be empty");if(ids.has(vote.agentId))throw new ConsensusArbitrationError(`Duplicate vote from agent ${vote.agentId}`);ids.add(vote.agentId);if(!Number.isFinite(vote.evidenceWeight)||vote.evidenceWeight<0||vote.evidenceWeight>1)throw new ConsensusArbitrationError(`Invalid evidence weight from agent ${vote.agentId}`);}}
private groupVotes(votes:readonly ArbitrationVote<T>[]):readonly WeightedGroup<T>[] {const groups=new Map<string,{state:T;weight:number;voters:string[]}>();const totalWeight=votes.reduce((sum,vote)=>sum+Math.max(vote.evidenceWeight,0),0);const normalizedTotal=totalWeight>0?totalWeight:votes.length;for(const vote of votes){const key=JSON.stringify(vote.state);const contribution=totalWeight>0?vote.evidenceWeight/normalizedTotal:1/votes.length;const current=groups.get(key)??{state:vote.state,weight:0,voters:[]};current.weight+=contribution;current.voters.push(vote.agentId);groups.set(key,current);}return Object.freeze([...groups.entries()].map(([key,group])=>Object.freeze({key,state:group.state,weight:group.weight,voters:Object.freeze(group.voters.slice().sort())})));}
private sameState(left:T,right:T):boolean{return JSON.stringify(left)===JSON.stringify(right);}}
