import { DeadlockDetector, type DependencyEdge, type DeadlockCycle } from "./consensus/DeadlockDetector.js";
import { SelfHealingStateResolver, type RecoveryHooks, type RecoveryResult } from "./consensus/SelfHealingStateResolver.js";
import type { ArbitrationDecision } from "./ConsensusArbitrator.js";
import type { SwarmDispatchRecord } from "./SwarmTaskDispatcher.js";

export type EpistemicState="UNKNOWN"|"CLAIMED"|"OBSERVED"|"EVIDENCE-SUPPORTED"|"VERIFIED";
export interface EpistemicTransition{readonly from:EpistemicState;readonly to:EpistemicState;readonly reason:string;}
export interface HealingSnapshot{readonly state:EpistemicState;readonly revision:number;readonly transitions:readonly EpistemicTransition[];}
export interface SelfHealingOutcome{readonly healed:boolean;readonly reason:string;readonly recovery?:RecoveryResult;readonly snapshot:HealingSnapshot;}
export class SelfHealingBridgeError extends Error{readonly code="SELF_HEALING_BRIDGE_ERROR" as const;constructor(message:string){super(message);this.name="SelfHealingBridgeError";}}
const STATE_RANK:Readonly<Record<EpistemicState,number>>=Object.freeze({UNKNOWN:0,CLAIMED:1,OBSERVED:2,"EVIDENCE-SUPPORTED":3,VERIFIED:4});
const ALLOWED_TRANSITIONS:Readonly<Record<EpistemicState,readonly EpistemicState[]>>=Object.freeze({UNKNOWN:["CLAIMED","OBSERVED"],CLAIMED:["OBSERVED","EVIDENCE-SUPPORTED"],OBSERVED:["EVIDENCE-SUPPORTED"],"EVIDENCE-SUPPORTED":["VERIFIED"],VERIFIED:[]});
export class SelfHealingBridge<T=readonly SwarmDispatchRecord[]>{private readonly detector:DeadlockDetector;private readonly resolver:SelfHealingStateResolver<T>;private snapshotState:HealingSnapshot=Object.freeze({state:"UNKNOWN",revision:0,transitions:Object.freeze([])});constructor(hooks:RecoveryHooks<T>,detector:DeadlockDetector=new DeadlockDetector()){this.detector=detector;this.resolver=new SelfHealingStateResolver<T>(hooks);}get snapshot():HealingSnapshot{return this.snapshotState;}
transition(to:EpistemicState,reason:string):HealingSnapshot{if(!reason.trim())throw new SelfHealingBridgeError("Epistemic transition reason must not be empty");const from=this.snapshotState.state;if(to!==from&&!ALLOWED_TRANSITIONS[from].includes(to))throw new SelfHealingBridgeError(`Invalid epistemic transition ${from} -> ${to}`);if(STATE_RANK[to]<STATE_RANK[from])throw new SelfHealingBridgeError(`Epistemic regression ${from} -> ${to} is forbidden`);return this.commitSnapshot(to,reason,to!==from);}
observeDispatch(records:readonly SwarmDispatchRecord[]):HealingSnapshot{if(records.length===0)return this.snapshot;const successful=records.every(record=>record.status==="SUCCEEDED");const evidenceSupported=records.some(record=>record.epistemicState==="EVIDENCE-SUPPORTED"||record.epistemicState==="VERIFIED");const verified=records.every(record=>record.epistemicState==="VERIFIED");this.transition(successful?"OBSERVED":"CLAIMED","Swarm dispatch produced task observations");if(evidenceSupported)this.transition("EVIDENCE-SUPPORTED","Swarm returned evidence-bearing observations");if(verified)this.transition("VERIFIED","All dispatched tasks reported VERIFIED state");return this.snapshot;}
arbitrate(decision:ArbitrationDecision<unknown>):HealingSnapshot{if(decision.disposition==="ACCEPT"){if(STATE_RANK[this.snapshotState.state]<STATE_RANK["EVIDENCE-SUPPORTED"])this.transition("EVIDENCE-SUPPORTED",`Consensus accepted with weighted support ${decision.weightedSupport.toFixed(6)}`);else this.record(`Consensus accepted with weighted support ${decision.weightedSupport.toFixed(6)}`);return this.snapshot;}const reason=`Consensus ${decision.disposition.toLowerCase()} the proposed swarm outcome`;if(STATE_RANK[this.snapshotState.state]<=STATE_RANK.CLAIMED)this.transition("CLAIMED",reason);else this.record(reason);return this.snapshot;}
async recoverConsensus(decision:ArbitrationDecision<unknown>,safeState:{readonly revision:number;readonly value:T},reason="Consensus recovery"):Promise<SelfHealingOutcome>{if(decision.disposition==="ACCEPT")return Object.freeze({healed:false,reason:"Consensus accepted; recovery not required",snapshot:this.snapshot});const recovery=await this.resolverRewind(safeState);this.snapshotState=Object.freeze({state:"UNKNOWN",revision:this.snapshotState.revision+1,transitions:Object.freeze([...this.snapshotState.transitions,Object.freeze({from:this.snapshotState.state,to:"UNKNOWN" as const,reason:`${reason}: ${decision.disposition.toLowerCase()} reset to safe state`})])});return Object.freeze({healed:true,reason,recovery,snapshot:this.snapshotState});}
async heal(edges:readonly DependencyEdge[],safeState:{readonly revision:number;readonly value:T},reason="Deadlock recovery"):Promise<SelfHealingOutcome>{const cycles=this.detector.detect(edges);if(cycles.length===0)return Object.freeze({healed:false,reason:"No deadlock detected",snapshot:this.snapshot});const cycle=this.selectCycle(cycles);const recovery=await this.resolver.resolve(cycle,safeState);this.snapshotState=Object.freeze({state:"UNKNOWN",revision:this.snapshotState.revision+1,transitions:Object.freeze([...this.snapshotState.transitions,Object.freeze({from:this.snapshotState.state,to:"UNKNOWN" as const,reason:`${reason}: state reset after recovery`})])});return Object.freeze({healed:recovery.rewound,reason,recovery,snapshot:this.snapshotState});}
private async resolverRewind(safeState:{readonly revision:number;readonly value:T}):Promise<RecoveryResult>{return this.resolver.resolve({participants:Object.freeze(["consensus"]),edges:Object.freeze([{waiter:"consensus",holder:"consensus",resource:"consensus-recovery"}])},safeState).catch(error=>{throw new SelfHealingBridgeError(`Consensus recovery failed: ${error instanceof Error?error.message:String(error)}`);});}
private record(reason:string):HealingSnapshot{return this.commitSnapshot(this.snapshotState.state,reason,false);}
private commitSnapshot(to:EpistemicState,reason:string,incrementRevision:boolean):HealingSnapshot{const transition:EpistemicTransition=Object.freeze({from:this.snapshotState.state,to,reason});this.snapshotState=Object.freeze({state:to,revision:this.snapshotState.revision+(incrementRevision?1:0),transitions:Object.freeze([...this.snapshotState.transitions,transition])});return this.snapshotState;}
private selectCycle(cycles:readonly DeadlockCycle[]):DeadlockCycle{return [...cycles].sort((a,b)=>a.participants.slice().sort().join("|").localeCompare(b.participants.slice().sort().join("|")))[0];}}
