import type { CompiledTaskGraph, IntentGraphTask, IntentTaskKind } from "./TaskGraphCompiler.js";
import type { ExecutionStrategy } from "./ExecutionPlanner.js";
import type { IntentSpec } from "./IntentSpec.js";

export type AgentRole = "ARCHITECT" | "BUILDER" | "VALIDATOR" | "EVIDENCE";
export interface SwarmAgent { readonly agentId: string; readonly role: AgentRole; readonly execute: (task: IntentGraphTask, context: SwarmExecutionContext) => Promise<SwarmTaskResult>; }
export interface SwarmExecutionContext { readonly intent: IntentSpec; readonly strategy: ExecutionStrategy; readonly taskId: string; readonly agentId: string; readonly signal: AbortSignal; }
export type SwarmEpistemicState = "UNKNOWN" | "CLAIMED" | "OBSERVED" | "EVIDENCE-SUPPORTED" | "VERIFIED";
export interface SwarmTaskResult { readonly status: "SUCCEEDED" | "REJECTED"; readonly epistemicState: SwarmEpistemicState; readonly evidenceWeight: number; readonly value: string; readonly reason?: string; }
export interface SwarmDispatchRecord { readonly taskId: string; readonly agentId: string; readonly role: AgentRole; readonly status: SwarmTaskResult["status"]; readonly epistemicState: SwarmEpistemicState; readonly evidenceWeight: number; readonly value: string; readonly reason?: string; }
export interface SwarmDispatchResult { readonly status: "SUCCEEDED" | "REJECTED" | "CANCELLED"; readonly records: readonly SwarmDispatchRecord[]; readonly peakConcurrency: number; }
export class SwarmDispatchError extends Error { readonly code = "SWARM_DISPATCH_ERROR" as const; constructor(message: string){super(message);this.name="SwarmDispatchError";} }
const TASK_ROLE: Readonly<Record<IntentTaskKind,AgentRole>>=Object.freeze({OBJECTIVE:"ARCHITECT",DEPENDENCY:"BUILDER",CONSTRAINT_CHECK:"BUILDER",ACCEPTANCE_CHECK:"VALIDATOR",EVIDENCE_CHECK:"EVIDENCE"});
export class SwarmTaskDispatcher {
 async dispatch(intent:IntentSpec,graph:CompiledTaskGraph,strategy:ExecutionStrategy,agents:readonly SwarmAgent[],signal?:AbortSignal):Promise<SwarmDispatchResult>{
  this.assertIdentity(intent,graph,strategy); const agentByRole=this.indexAgents(agents); const records=new Map<string,SwarmDispatchRecord>(); const controller=new AbortController(); const abort=()=>controller.abort(signal?.reason); if(signal?.aborted)abort(); else signal?.addEventListener("abort",abort,{once:true}); let active=0; let peak=0;
  try{for(const layer of graph.resolution.layers){if(controller.signal.aborted)return this.cancel(records,peak);const runnable=[...layer].sort((a,b)=>a.id.localeCompare(b.id));for(let offset=0;offset<runnable.length;offset+=strategy.maxConcurrency){const batch=runnable.slice(offset,offset+strategy.maxConcurrency);const settled=await Promise.all(batch.map(async(task)=>{if(controller.signal.aborted)return false;if((task.dependsOn??[]).some(dep=>!records.has(dep)||records.get(dep)?.status!=="SUCCEEDED"))throw new SwarmDispatchError(`Task ${task.id} has an unsatisfied dependency`);const role=TASK_ROLE[task.kind];const agent=this.selectAgent(agentByRole.get(role)??[],task.id);active+=1;peak=Math.max(peak,active);try{const result=await agent.execute(task,{intent,strategy,taskId:task.id,agentId:agent.agentId,signal:controller.signal});if(!Number.isFinite(result.evidenceWeight)||result.evidenceWeight<0||result.evidenceWeight>1)throw new SwarmDispatchError(`Agent ${agent.agentId} returned an invalid evidence weight`);records.set(task.id,Object.freeze({taskId:task.id,agentId:agent.agentId,role,status:result.status,epistemicState:result.epistemicState,evidenceWeight:result.evidenceWeight,value:result.value,...(result.reason===undefined?{}:{reason:result.reason})}));return result.status==="SUCCEEDED";}finally{active-=1;}}));if(settled.some(ok=>!ok))return Object.freeze({status:"REJECTED",records:this.sortedRecords(records),peakConcurrency:peak});}}
   const status=[...records.values()].every(r=>r.status==="SUCCEEDED")?"SUCCEEDED":"REJECTED";return Object.freeze({status,records:this.sortedRecords(records),peakConcurrency:peak});
  }catch(error){controller.abort(error);throw error;}finally{signal?.removeEventListener("abort",abort);}
 }
 private assertIdentity(intent:IntentSpec,graph:CompiledTaskGraph,strategy:ExecutionStrategy):void{if(intent.intentId!==graph.intentId||intent.contentHash!==graph.contentHash)throw new SwarmDispatchError("Intent and graph identity mismatch");if(intent.intentId!==strategy.intentId||intent.contentHash!==strategy.contentHash)throw new SwarmDispatchError("Intent and execution strategy identity mismatch");if(!Number.isInteger(strategy.maxConcurrency)||strategy.maxConcurrency<1||strategy.maxConcurrency>intent.resourceBudget.maxConcurrentTasks)throw new SwarmDispatchError("Execution strategy violates the intent concurrency budget");}
 private indexAgents(agents:readonly SwarmAgent[]):ReadonlyMap<AgentRole,readonly SwarmAgent[]>{const byRole=new Map<AgentRole,SwarmAgent[]>();for(const agent of agents){if(!agent.agentId.trim())throw new SwarmDispatchError("Agent id must not be empty");const group=byRole.get(agent.role)??[];group.push(agent);byRole.set(agent.role,group);}for(const group of byRole.values())group.sort((a,b)=>a.agentId.localeCompare(b.agentId));return byRole;}
 private selectAgent(agents:readonly SwarmAgent[],taskId:string):SwarmAgent{if(agents.length===0)throw new SwarmDispatchError(`No swarm agent available for task ${taskId}`);const index=[...taskId].reduce((sum,ch)=>sum+ch.charCodeAt(0),0)%agents.length;return agents[index];}
 private sortedRecords(records:ReadonlyMap<string,SwarmDispatchRecord>):readonly SwarmDispatchRecord[]{return Object.freeze([...records.values()].sort((a,b)=>a.taskId.localeCompare(b.taskId)));}
 private cancel(records:ReadonlyMap<string,SwarmDispatchRecord>,peakConcurrency:number):SwarmDispatchResult{return Object.freeze({status:"CANCELLED",records:this.sortedRecords(records),peakConcurrency});}
}
