#!/usr/bin/env node
/**
 * =============================================================================
 * KLYN AI OS — GENESIS EVOLUTION FORGE
 * File: genesis/forge.mjs
 *
 * Materializes the Genesis V671–V700 evolution layers from
 * genesis/evolution-manifest.json. Every layer gets:
 *   - genesis/vXXX/        dedicated layer directory
 *   - 10 core TS modules   (kernel, orchestrator, runtime, controller, engine,
 *                           registry, coordinator, observer, adapter, platform)
 *   - smoke.ts             per-layer self-test (10 checks)
 *   - layer.json           canonical manifest copy
 *   - README.md            architecture doc
 *   - genesis-vXXX-bootstrap.sh  root-level Termux/Linux bootstrap script
 *
 * Plain Node ESM (.mjs) — no dependencies, no build step, no TS toolchain
 * required to run. Compatible with Termux and Linux.
 *
 * Usage:
 *   node genesis/forge.mjs list
 *   node genesis/forge.mjs v671
 *   node genesis/forge.mjs all
 *   node genesis/forge.mjs verify
 * =============================================================================
 */

import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const GENESIS = join(ROOT, 'genesis');
const MANIFEST_FILE = join(GENESIS, 'evolution-manifest.json');
const manifest = JSON.parse(readFileSync(MANIFEST_FILE, 'utf8'));

/* ---------------------------------------------------------------------------
 * Small helpers
 * ------------------------------------------------------------------------- */

const versionOf = (id) => 'V' + id.slice(1);

function banner(cfg, fileDesc, role) {
  return [
    '/**',
    ' * =============================================================================',
    ' * KLYN AI OS — GENESIS ' + cfg.id + ' — ' + cfg.name,
    ' * Module: ' + fileDesc + ' (role: ' + role + ')',
    ' * Mission: ' + cfg.mission,
    ' * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs ' + cfg.id + '` to regenerate.',
    ' * =============================================================================',
    ' */',
  ].join('\n');
}

function contractsLiteral(cfg) {
  return '[' + cfg.contracts.map((c) => "'" + c + "'").join(', ') + ']';
}

function policiesLiteral(p) {
  return [
    '{',
    '      maxEntities: ' + p.maxEntities + ',',
    '      tickMs: ' + p.tickMs + ',',
    '      batchSize: ' + p.batchSize + ',',
    '      ringSize: ' + p.ringSize + ',',
    '      consensusThreshold: ' + p.consensusThreshold + ',',
    '      compactionThreshold: ' + p.compactionThreshold + ',',
    '      quota: ' + p.quota + ',',
    '    }',
  ].join('\n');
}

const SHARED_IMPORT = "import { Logger, EventBus, RingBuffer, TokenBucket, monotonic, normalizePolicies } from '../platform/modules.js';";
const SHARED_TYPE_IMPORT = "import type { LayerModule, PolicySet, ResolvedPolicies } from '../platform/modules.js';";

/* ---------------------------------------------------------------------------
 * Module templates (1 of 10) — Kernel: module registry + health
 * ------------------------------------------------------------------------- */

function tKernel(cfg) {
  const K = cfg.modules[0];
  return [
    banner(cfg, K + '.ts', 'kernel'),
    '',
    "import { Logger } from '../platform/modules.js';",
    "import type { LayerModule } from '../platform/modules.js';",
    '',
    'export interface KernelRecord {',
    '  name: string;',
    "  role: string;",
    "  status: 'registered' | 'started' | 'stopped';",
    '  registeredAt: number;',
    '}',
    '',
    'export interface KernelHealth {',
    '  ready: boolean;',
    '  registered: number;',
    '  started: number;',
    '  stopped: number;',
    '}',
    '',
    'export class ' + K + ' implements LayerModule {',
    "  readonly name = '" + K + "';",
    "  readonly role = 'kernel';",
    '  readonly layer: string;',
    '  readonly codename: string;',
    '  readonly #records = new Map<string, KernelRecord>();',
    '  readonly #log: Logger;',
    '  #bootStartedAt = 0;',
    '',
    '  constructor(layer: string, codename: string, quiet = false) {',
    '    this.layer = layer;',
    '    this.codename = codename;',
    "    this.#log = new Logger(layer + ':' + this.role, quiet ? 3 : 1);",
    '  }',
    '',
    '  start(): void {',
    '    this.#bootStartedAt = Date.now();',
    "    this.#log.info('kernel module started');",
    '  }',
    '',
    '  stop(): void {',
    "    this.#log.info('kernel module stopped');",
    '  }',
    '',
    '  register(module: LayerModule): KernelRecord {',
    '    const existing = this.#records.get(module.name);',
    '    const record: KernelRecord = {',
    '      name: module.name,',
    '      role: module.role,',
    '      status: existing ? existing.status : \'registered\',',
    '      registeredAt: existing ? existing.registeredAt : Date.now(),',
    '    };',
    '    this.#records.set(module.name, record);',
    '    return record;',
    '  }',
    '',
    '  markStarted(name: string): void {',
    '    const record = this.#records.get(name);',
    "    if (record) record.status = 'started';",
    '  }',
    '',
    '  markStopped(name: string): void {',
    '    const record = this.#records.get(name);',
    "    if (record) record.status = 'stopped';",
    '  }',
    '',
    '  get size(): number {',
    '    return this.#records.size;',
    '  }',
    '',
    '  names(): string[] {',
    '    return [...this.#records.keys()];',
    '  }',
    '',
    '  records(): KernelRecord[] {',
    '    return [...this.#records.values()];',
    '  }',
    '',
    '  bootStartedAt(): number {',
    '    return this.#bootStartedAt;',
    '  }',
    '',
    '  health(): KernelHealth {',
    '    let started = 0;',
    '    let stopped = 0;',
    '    for (const record of this.#records.values()) {',
    "      if (record.status === 'started') started += 1;",
    "      if (record.status === 'stopped') stopped += 1;",
    '    }',
    '    const registered = this.#records.size;',
    '    return { ready: registered > 0 && started === registered, registered, started, stopped };',
    '  }',
    '',
    '  destroy(): void {',
    '    this.#records.clear();',
    '  }',
    '}',
    '',
  ].join('\n');
}

/* ---------------------------------------------------------------------------
 * Module templates (2 of 10) — Orchestrator: ordered boot + reverse shutdown
 * ------------------------------------------------------------------------- */

function tOrchestrator(cfg) {
  const O = cfg.modules[1];
  return [
    banner(cfg, O + '.ts', 'orchestrator'),
    '',
    "import { Logger, monotonic } from '../platform/modules.js';",
    "import type { LayerModule } from '../platform/modules.js';",
    '',
    'export interface BootReport {',
    '  order: string[];',
    '  totalMs: number;',
    '  failures: string[];',
    '}',
    '',
    'export class ' + O + ' implements LayerModule {',
    "  readonly name = '" + O + "';",
    "  readonly role = 'orchestrator';",
    '  readonly layer: string;',
    '  readonly #log: Logger;',
    '',
    '  constructor(layer: string, quiet = false) {',
    '    this.layer = layer;',
    "    this.#log = new Logger(layer + ':' + this.role, quiet ? 3 : 1);",
    '  }',
    '',
    '  start(): void { /* orchestrator lifecycle is driven by the platform handle */ }',
    '  stop(): void { /* orchestrator lifecycle is driven by the platform handle */ }',
    '',
    '  async boot(modules: LayerModule[], order: string[]): Promise<BootReport> {',
    '    const failures: string[] = [];',
    '    const startedAt = monotonic();',
    '    for (const name of order) {',
    '      let found: LayerModule | undefined;',
    '      for (const module of modules) {',
    "        if (module.name === name) { found = module; break; }",
    '      }',
    "      if (!found) { failures.push('missing:' + name); continue; }",
    '      try {',
    '        await found.start();',
    '      } catch (err) {',
    '        failures.push(name + \':\' + String(err));',
    '      }',
    '    }',
    '    const totalMs = Math.round((monotonic() - startedAt) * 100) / 100;',
    "    if (failures.length > 0) this.#log.warn('boot failures: ' + failures.join(', '));",
    '    return { order: [...order], totalMs, failures };',
    '  }',
    '',
    '  async shutdown(modules: LayerModule[]): Promise<void> {',
    '    for (let i = modules.length - 1; i >= 0; i -= 1) {',
    '      const module = modules[i];',
    '      if (!module) continue;',
    '      try {',
    '        await module.stop();',
    '      } catch {',
    '        /* best-effort shutdown */',
    '      }',
    '    }',
    '  }',
    '}',
    '',
  ].join('\n');
}

/* ---------------------------------------------------------------------------
 * Module templates (3 of 10) — Runtime: guarded lifecycle state machine
 * ------------------------------------------------------------------------- */

function tRuntime(cfg) {
  const R = cfg.modules[2];
  return [
    banner(cfg, R + '.ts', 'runtime'),
    '',
    "import type { LayerModule } from '../platform/modules.js';",
    '',
    "export type RuntimeState = 'idle' | 'booting' | 'ready' | 'running' | 'draining' | 'stopped';",
    '',
    'const ALLOWED_TRANSITIONS: Record<RuntimeState, RuntimeState[]> = {',
    "  idle: ['booting'],",
    "  booting: ['ready', 'stopped'],",
    "  ready: ['running', 'stopped'],",
    "  running: ['draining', 'stopped'],",
    "  draining: ['stopped'],",
    '  stopped: [],',
    '};',
    '',
    'export class ' + R + ' implements LayerModule {',
    "  readonly name = '" + R + "';",
    "  readonly role = 'runtime';",
    '  readonly layer: string;',
    "  #state: RuntimeState = 'idle';",
    '  #transitions = new Map<RuntimeState, Set<() => void>>();',
    '  #enteredRunningAt = 0;',
    '',
    '  constructor(layer: string) {',
    '    this.layer = layer;',
    '  }',
    '',
    '  start(): void { /* lifecycle is driven by the platform handle */ }',
    '  stop(): void { /* lifecycle is driven by the platform handle */ }',
    '',
    '  get state(): RuntimeState {',
    '    return this.#state;',
    '  }',
    '',
    '  onEnter(state: RuntimeState, callback: () => void): () => void {',
    '    let set = this.#transitions.get(state);',
    '    if (!set) {',
    '      set = new Set();',
    '      this.#transitions.set(state, set);',
    '    }',
    '    set.add(callback);',
    '    return () => {',
    '      if (set) set.delete(callback);',
    '    };',
    '  }',
    '',
    '  transition(next: RuntimeState): void {',
    '    const allowed = ALLOWED_TRANSITIONS[this.#state];',
    "    if (!allowed || allowed.indexOf(next) < 0) {",
    "      throw new Error(this.layer + ': illegal transition ' + this.#state + ' -> ' + next);",
    '    }',
    '    this.#state = next;',
    "    if (next === 'running') this.#enteredRunningAt = Date.now();",
    '    const set = this.#transitions.get(next);',
    '    if (set) {',
    '      for (const callback of set) {',
    '        try {',
    '          callback();',
    '        } catch {',
    '          /* subscriber isolation */',
    '        }',
    '      }',
    '    }',
    '  }',
    '',
    '  uptimeMs(): number {',
    '    return this.#enteredRunningAt > 0 ? Date.now() - this.#enteredRunningAt : 0;',
    '  }',
    '}',
    '',
  ].join('\n');
}

/* ---------------------------------------------------------------------------
 * Module templates (4 of 10) — Controller: policy enforcement + quotas
 * ------------------------------------------------------------------------- */

function tController(cfg) {
  const C = cfg.modules[3];
  return [
    banner(cfg, C + '.ts', 'controller'),
    '',
    "import { Logger, TokenBucket } from '../platform/modules.js';",
    "import type { LayerModule, ResolvedPolicies } from '../platform/modules.js';",
    '',
    'export interface GateResult {',
    '  allowed: boolean;',
    '  reason: string;',
    '}',
    '',
    'export interface PolicySnapshot {',
    '  maxEntities: number;',
    '  tickMs: number;',
    '  batchSize: number;',
    '  ringSize: number;',
    '  consensusThreshold: number;',
    '  compactionThreshold: number;',
    '  quota: number;',
    '}',
    '',
    'export class ' + C + ' implements LayerModule {',
    "  readonly name = '" + C + "';",
    "  readonly role = 'controller';",
    '  readonly layer: string;',
    '  readonly #policies: ResolvedPolicies;',
    '  readonly #buckets = new Map<string, TokenBucket>();',
    '  readonly #log: Logger;',
    '',
    '  constructor(layer: string, policies: ResolvedPolicies, quiet = false) {',
    '    this.layer = layer;',
    '    this.#policies = policies;',
    "    this.#log = new Logger(layer + ':' + this.role, quiet ? 3 : 1);",
    '  }',
    '',
    '  start(): void {}',
    '  stop(): void {}',
    '',
    '  policies(): PolicySnapshot {',
    '    return {',
    '      maxEntities: this.#policies.maxEntities,',
    '      tickMs: this.#policies.tickMs,',
    '      batchSize: this.#policies.batchSize,',
    '      ringSize: this.#policies.ringSize,',
    '      consensusThreshold: this.#policies.consensusThreshold,',
    '      compactionThreshold: this.#policies.compactionThreshold,',
    '      quota: this.#policies.quota,',
    '    };',
    '  }',
    '',
    '  admit(scope: string, weight = 1): GateResult {',
    '    let bucket = this.#buckets.get(scope);',
    '    if (!bucket) {',
    '      bucket = new TokenBucket(this.#policies.quota, this.#policies.quota / 1000);',
    '      this.#buckets.set(scope, bucket);',
    '    }',
    '    const allowed = bucket.take(weight);',
    "    return { allowed, reason: allowed ? 'ok' : 'quota exceeded: ' + scope };",
    '  }',
    '',
    '  requireReady(state: string): GateResult {',
    "    const allowed = state === 'running';",
    "    return { allowed, reason: allowed ? 'ok' : 'layer not ready: ' + state };",
    '  }',
    '',
    '  consensus(agree: number, total: number): boolean {',
    '    return total > 0 && agree / total >= this.#policies.consensusThreshold;',
    '  }',
    '',
    '  assert(condition: boolean, message: string): void {',
    "    if (!condition) throw new Error('[' + this.layer + '] ' + message);",
    '  }',
    '',
    '  reset(): void {',
    '    this.#buckets.clear();',
    "    this.#log.info('quota buckets reset');",
    '  }',
    '}',
    '',
  ].join('\n');
}

/* ---------------------------------------------------------------------------
 * Module templates (5 of 10) — Engine: bounded work queue + tick loop
 * ------------------------------------------------------------------------- */

function tEngine(cfg) {
  const E = cfg.modules[4];
  return [
    banner(cfg, E + '.ts', 'engine'),
    '',
    "import { EventBus, Logger, monotonic } from '../platform/modules.js';",
    "import type { LayerModule, ResolvedPolicies } from '../platform/modules.js';",
    '',
    'export type EngineTask = () => void | Promise<void>;',
    '',
    'export interface EngineStats {',
    '  processed: number;',
    '  errors: number;',
    '  totalMs: number;',
    '  lastTickMs: number;',
    '  queueDepth: number;',
    '}',
    '',
    'export class ' + E + ' implements LayerModule {',
    "  readonly name = '" + E + "';",
    "  readonly role = 'engine';",
    '  readonly layer: string;',
    '  readonly #policies: ResolvedPolicies;',
    '  readonly #bus: EventBus;',
    '  readonly #queue: EngineTask[] = [];',
    '  readonly #log: Logger;',
    '  #processed = 0;',
    '  #errors = 0;',
    '  #totalMs = 0;',
    '  #lastTickMs = 0;',
    '  #timer: ReturnType<typeof setInterval> | null = null;',
    '',
    '  constructor(layer: string, policies: ResolvedPolicies, bus: EventBus, quiet = false) {',
    '    this.layer = layer;',
    '    this.#policies = policies;',
    '    this.#bus = bus;',
    "    this.#log = new Logger(layer + ':' + this.role, quiet ? 3 : 1);",
    '  }',
    '',
    '  start(): void {',
    '    if (this.#timer) return;',
    '    this.#timer = setInterval(() => {',
    '      void this.tick();',
    '    }, Math.max(5, this.#policies.tickMs));',
    '    if (this.#timer.unref) this.#timer.unref();',
    '  }',
    '',
    '  stop(): void {',
    '    if (this.#timer) {',
    '      clearInterval(this.#timer);',
    '      this.#timer = null;',
    '    }',
    '  }',
    '',
    '  enqueue(task: EngineTask): void {',
    '    this.#queue.push(task);',
    "    this.#bus.emit(this.layer + '.engine.enqueued', { depth: this.#queue.length });",
    '  }',
    '',
    '  get depth(): number {',
    '    return this.#queue.length;',
    '  }',
    '',
    '  async tick(batch = this.#policies.batchSize): Promise<number> {',
    '    const startedAt = monotonic();',
    '    let done = 0;',
    '    while (done < batch) {',
    '      const task = this.#queue.shift();',
    '      if (!task) break;',
    '      try {',
    '        await task();',
    '        this.#processed += 1;',
    '      } catch {',
    '        this.#errors += 1;',
    '      }',
    '      done += 1;',
    '    }',
    '    this.#lastTickMs = Math.round((monotonic() - startedAt) * 100) / 100;',
    '    this.#totalMs += this.#lastTickMs;',
    '    if (done > 0) {',
    "      this.#bus.emit(this.layer + '.engine.tick', { processed: done, errors: this.#errors });",
    '    }',
    '    return done;',
    '  }',
    '',
    '  stats(): EngineStats {',
    '    return {',
    '      processed: this.#processed,',
    '      errors: this.#errors,',
    '      totalMs: Math.round(this.#totalMs * 100) / 100,',
    '      lastTickMs: this.#lastTickMs,',
    '      queueDepth: this.#queue.length,',
    '    };',
    '  }',
    '}',
    '',
  ].join('\n');
}

/* ---------------------------------------------------------------------------
 * Module templates (6 of 10) — Registry: O(1) LRU entity store
 * ------------------------------------------------------------------------- */

function tRegistry(cfg) {
  const G = cfg.modules[5];
  return [
    banner(cfg, G + '.ts', 'registry'),
    '',
    "import type { LayerModule } from '../platform/modules.js';",
    '',
    'export interface RegistryStats {',
    '  capacity: number;',
    '  size: number;',
    '  hits: number;',
    '  misses: number;',
    '  evictions: number;',
    '}',
    '',
    'export class ' + G + '<T = unknown> implements LayerModule {',
    "  readonly name = '" + G + "';",
    "  readonly role = 'registry';",
    '  readonly layer: string;',
    '  readonly #capacity: number;',
    '  readonly #map = new Map<string, T>();',
    '  #hits = 0;',
    '  #misses = 0;',
    '  #evictions = 0;',
    '',
    '  constructor(layer: string, capacity = 1024) {',
    '    this.layer = layer;',
    '    this.#capacity = Math.max(1, capacity | 0);',
    '  }',
    '',
    '  start(): void {}',
    '  stop(): void {}',
    '',
    '  set(key: string, value: T): void {',
    '    if (this.#map.has(key)) this.#map.delete(key);',
    '    this.#map.set(key, value);',
    '    if (this.#map.size > this.#capacity) {',
    '      const oldest = this.#map.keys().next().value;',
    '      if (oldest !== undefined) {',
    '        this.#map.delete(oldest);',
    '        this.#evictions += 1;',
    '      }',
    '    }',
    '  }',
    '',
    '  get(key: string): T | undefined {',
    '    const value = this.#map.get(key);',
    '    if (value === undefined) {',
    '      this.#misses += 1;',
    '      return undefined;',
    '    }',
    '    this.#map.delete(key);',
    '    this.#map.set(key, value);',
    '    this.#hits += 1;',
    '    return value;',
    '  }',
    '',
    '  has(key: string): boolean {',
    '    return this.#map.has(key);',
    '  }',
    '',
    '  evict(key: string): boolean {',
    '    return this.#map.delete(key);',
    '  }',
    '',
    '  clear(): void {',
    '    this.#map.clear();',
    '  }',
    '',
    '  get size(): number {',
    '    return this.#map.size;',
    '  }',
    '',
    '  snapshot(): Array<[string, T]> {',
    '    return [...this.#map.entries()];',
    '  }',
    '',
    '  stats(): RegistryStats {',
    '    return {',
    '      capacity: this.#capacity,',
    '      size: this.#map.size,',
    '      hits: this.#hits,',
    '      misses: this.#misses,',
    '      evictions: this.#evictions,',
    '    };',
    '  }',
    '}',
    '',
  ].join('\n');
}

/* ---------------------------------------------------------------------------
 * Module templates (7 of 10) — Coordinator: contract-gated message bus
 * ------------------------------------------------------------------------- */

function tCoordinator(cfg) {
  const H = cfg.modules[6];
  return [
    banner(cfg, H + '.ts', 'coordinator'),
    '',
    "import { EventBus } from '../platform/modules.js';",
    "import type { LayerModule } from '../platform/modules.js';",
    '',
    'export type TopicHandler = (payload: unknown) => void;',
    'export type Unsubscribe = () => void;',
    '',
    'export class ' + H + ' implements LayerModule {',
    "  readonly name = '" + H + "';",
    "  readonly role = 'coordinator';",
    '  readonly layer: string;',
    '  readonly #bus: EventBus;',
    '  readonly #contracts: ReadonlySet<string>;',
    '',
    '  constructor(layer: string, contracts: readonly string[], bus: EventBus) {',
    '    this.layer = layer;',
    '    this.#contracts = new Set(contracts);',
    '    this.#bus = bus;',
    '  }',
    '',
    '  start(): void {}',
    '  stop(): void {}',
    '',
    '  on(topic: string, handler: TopicHandler): Unsubscribe {',
    '    return this.#bus.on(topic, handler);',
    '  }',
    '',
    '  emit(topic: string, payload?: unknown): number {',
    '    return this.#bus.emit(topic, payload);',
    '  }',
    '',
    '  contracts(): string[] {',
    '    return [...this.#contracts];',
    '  }',
    '',
    '  topics(): string[] {',
    '    return this.#bus.topics();',
    '  }',
    '',
    '  isContract(topic: string): boolean {',
    '    return this.#contracts.has(topic);',
    '  }',
    '',
    '  get delivered(): number {',
    '    return this.#bus.delivered;',
    '  }',
    '',
    '  clear(): void {',
    '    this.#bus.clear();',
    '  }',
    '}',
    '',
  ].join('\n');
}

/* ---------------------------------------------------------------------------
 * Module templates (8 of 10) — Observer: ring-buffered telemetry
 * ------------------------------------------------------------------------- */

function tObserver(cfg) {
  const V = cfg.modules[7];
  return [
    banner(cfg, V + '.ts', 'observer'),
    '',
    "import { RingBuffer } from '../platform/modules.js';",
    "import type { LayerModule } from '../platform/modules.js';",
    '',
    'export interface MetricSummary {',
    '  count: number;',
    '  sum: number;',
    '  min: number;',
    '  max: number;',
    '  avg: number;',
    '  last: number;',
    '}',
    '',
    'export class ' + V + ' implements LayerModule {',
    "  readonly name = '" + V + "';",
    "  readonly role = 'observer';",
    '  readonly layer: string;',
    '  readonly #ringSize: number;',
    '  readonly #rings = new Map<string, RingBuffer<number>>();',
    '  #events = 0;',
    '',
    '  constructor(layer: string, ringSize = 256) {',
    '    this.layer = layer;',
    '    this.#ringSize = Math.max(8, ringSize | 0);',
    '  }',
    '',
    '  start(): void {}',
    '  stop(): void {}',
    '',
    '  record(name: string, value: number): void {',
    '    let ring = this.#rings.get(name);',
    '    if (!ring) {',
    '      ring = new RingBuffer<number>(this.#ringSize);',
    '      this.#rings.set(name, ring);',
    '    }',
    '    ring.push(value);',
    '    this.#events += 1;',
    '  }',
    '',
    '  timing(name: string, ms: number): void {',
    '    this.record(name, ms);',
    '  }',
    '',
    '  count(name: string): number {',
    '    const ring = this.#rings.get(name);',
    '    return ring ? ring.size : 0;',
    '  }',
    '',
    '  last(name: string): number | undefined {',
    '    const ring = this.#rings.get(name);',
    '    return ring ? ring.last() : undefined;',
    '  }',
    '',
    '  summary(name: string): MetricSummary | undefined {',
    '    const ring = this.#rings.get(name);',
    '    if (!ring || ring.size === 0) return undefined;',
    '    const values = ring.toArray();',
    '    let sum = 0;',
    '    let min = Number.POSITIVE_INFINITY;',
    '    let max = Number.NEGATIVE_INFINITY;',
    '    for (const value of values) {',
    '      sum += value;',
    '      if (value < min) min = value;',
    '      if (value > max) max = value;',
    '    }',
    '    const count = values.length;',
    '    return {',
    '      count,',
    '      sum,',
    '      min,',
    '      max,',
    '      avg: sum / count,',
    '      last: values[count - 1] as number,',
    '    };',
    '  }',
    '',
    '  snapshot(): Record<string, MetricSummary> {',
    '    const out: Record<string, MetricSummary> = {};',
    '    for (const name of this.#rings.keys()) {',
    '      const summary = this.summary(name);',
    '      if (summary) out[name] = summary;',
    '    }',
    '    return out;',
    '  }',
    '',
    '  get totalEvents(): number {',
    '    return this.#events;',
    '  }',
    '',
    '  reset(): void {',
    '    this.#rings.clear();',
    '    this.#events = 0;',
    '  }',
    '}',
    '',
  ].join('\n');
}

/* ---------------------------------------------------------------------------
 * Module templates (9 of 10) — Adapter: environment probe + boundary calls
 * ------------------------------------------------------------------------- */

function tAdapter(cfg) {
  const A = cfg.modules[8];
  return [
    banner(cfg, A + '.ts', 'adapter'),
    '',
    "import { Logger, monotonic } from '../platform/modules.js';",
    "import type { LayerModule } from '../platform/modules.js';",
    '',
    'export interface ProbeCheck {',
    '  name: string;',
    '  ok: boolean;',
    '  detail: string;',
    '}',
    '',
    'export interface ProbeResult {',
    '  ok: boolean;',
    '  latencyMs: number;',
    '  checks: ProbeCheck[];',
    '}',
    '',
    'export interface CallResult {',
    '  boundary: string;',
    '  accepted: boolean;',
    '  reason: string;',
    '}',
    '',
    'export class ' + A + ' implements LayerModule {',
    "  readonly name = '" + A + "';",
    "  readonly role = 'adapter';",
    '  readonly layer: string;',
    '  readonly #boundaries: ReadonlySet<string>;',
    '  readonly #log: Logger;',
    '',
    '  constructor(layer: string, boundaries: readonly string[], quiet = false) {',
    '    this.layer = layer;',
    '    this.#boundaries = new Set(boundaries);',
    "    this.#log = new Logger(layer + ':' + this.role, quiet ? 3 : 1);",
    '  }',
    '',
    '  start(): void {}',
    '  stop(): void {}',
    '',
    '  probe(): ProbeResult {',
    '    const startedAt = monotonic();',
    '    const checks: ProbeCheck[] = [];',
    "    const nodeVersion = typeof process !== 'undefined' ? process.version : 'unknown';",
    "    checks.push({ name: 'node-runtime', ok: nodeVersion !== 'unknown', detail: nodeVersion });",
    "    const home = typeof process !== 'undefined' ? process.env.HOME || process.env.USERPROFILE || '' : '';",
    "    checks.push({ name: 'home-directory', ok: home.length > 0, detail: home || 'unset' });",
    '    checks.push({',
    "      name: 'working-directory',",
    "      ok: typeof process !== 'undefined' && typeof process.cwd === 'function',",
    "      detail: typeof process !== 'undefined' ? process.cwd() : 'n/a',",
    '    });',
    "    checks.push({ name: 'layer-contracts', ok: this.#boundaries.size > 0, detail: String(this.#boundaries.size) });",
    '    const latencyMs = Math.round((monotonic() - startedAt) * 1000) / 1000;',
    '    const ok = checks.every((check) => check.ok);',
    "    if (!ok) this.#log.warn('environment probe reported failures');",
    '    return { ok, latencyMs, checks };',
    '  }',
    '',
    '  call(boundary: string, payload?: unknown): CallResult {',
    '    const accepted = this.#boundaries.has(boundary);',
    "    if (accepted && payload !== undefined) this.#log.info('call accepted on ' + boundary);",
    "    return { boundary, accepted, reason: accepted ? 'ok' : 'unknown boundary: ' + boundary };",
    '  }',
    '',
    '  boundaries(): string[] {',
    '    return [...this.#boundaries];',
    '  }',
    '}',
    '',
  ].join('\n');
}

/* ---------------------------------------------------------------------------
 * Module templates (10 of 10) — Platform: composition root + public API
 * ------------------------------------------------------------------------- */

function tPlatform(cfg) {
  const P = cfg.modules[9];
  return [
    banner(cfg, P + '.ts', 'platform — composition root'),
    '',
    "import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';",
    "import type { LayerModule, PolicySet } from '../platform/modules.js';",
    '',
    ...cfg.modules.slice(0, 9).map((m, i) => {
      const roleNames = ['kernel', 'orchestrator', 'runtime', 'controller', 'engine', 'registry', 'coordinator', 'observer', 'adapter'];
      return "import { " + m + " } from './" + m + ".js';" + (i === 8 ? '' : '');
    }),
    "import type { BootReport } from './" + cfg.modules[1] + ".js';",
    "import type { EngineStats } from './" + cfg.modules[4] + ".js';",
    '',
    'export interface LayerInfo {',
    '  id: string;',
    '  name: string;',
    '  codename: string;',
    '  version: string;',
    '}',
    '',
    'export const LAYER: LayerInfo = Object.freeze({',
    "  id: '" + cfg.id + "',",
    "  name: '" + cfg.name + "',",
    "  codename: '" + cfg.codename + "',",
    "  version: '" + versionOf(cfg.id) + "',",
    '});',
    '',
    'export const CONTRACTS: readonly string[] = Object.freeze(' + contractsLiteral(cfg) + ');',
    '',
    'const LAYER_POLICIES = ' + policiesLiteral(cfg.policies) + ';',
    '',
    'export interface LayerHealth {',
    '  ready: boolean;',
    '  registered: number;',
    '  started: number;',
    '  state: string;',
    '  engine: EngineStats;',
    '}',
    '',
    'export interface LayerHandle {',
    '  info: LayerInfo;',
    '  kernel: ' + cfg.modules[0] + ';',
    '  orchestrator: ' + cfg.modules[1] + ';',
    '  runtime: ' + cfg.modules[2] + ';',
    '  controller: ' + cfg.modules[3] + ';',
    '  engine: ' + cfg.modules[4] + ';',
    '  registry: ' + cfg.modules[5] + ';',
    '  coordinator: ' + cfg.modules[6] + ';',
    '  observer: ' + cfg.modules[7] + ';',
    '  adapter: ' + cfg.modules[8] + ';',
    '  modules: LayerModule[];',
    '  start(): Promise<BootReport>;',
    '  stop(): Promise<void>;',
    '  health(): LayerHealth;',
    '}',
    '',
    'export class ' + P + ' implements LayerModule {',
    "  readonly name = '" + P + "';",
    "  readonly role = 'platform';",
    '  readonly layer: string;',
    '',
    '  constructor(layer: string) {',
    '    this.layer = layer;',
    '  }',
    '',
    '  start(): void { /* composition root: lifecycle is driven by the layer handle */ }',
    '  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }',
    '}',
    '',
    'export function createLayer(overrides?: PolicySet): LayerHandle {',
    '  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });',
    '  const bus = new EventBus();',
    '  const layer = LAYER.id;',
    '  const log = new Logger(LAYER.id);',
    '',
    '  const kernel = new ' + cfg.modules[0] + '(layer, LAYER.codename);',
    '  const orchestrator = new ' + cfg.modules[1] + '(layer);',
    '  const runtime = new ' + cfg.modules[2] + '(layer);',
    '  const controller = new ' + cfg.modules[3] + '(layer, policies);',
    '  const coordinator = new ' + cfg.modules[6] + '(layer, CONTRACTS, bus);',
    '  const engine = new ' + cfg.modules[4] + '(layer, policies, bus);',
    '  const registry = new ' + cfg.modules[5] + '(layer, policies.maxEntities);',
    '  const observer = new ' + cfg.modules[7] + '(layer, policies.ringSize);',
    '  const adapter = new ' + cfg.modules[8] + '(layer, CONTRACTS);',
    '  const platform = new ' + P + '(layer);',
    '',
    '  const modules: LayerModule[] = [',
    '    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,',
    '  ];',
    '  const order: string[] = modules.map((module) => module.name);',
    '  for (const module of modules) kernel.register(module);',
    '',
    '  return {',
    '    info: LAYER,',
    '    kernel,',
    '    orchestrator,',
    '    runtime,',
    '    controller,',
    '    engine,',
    '    registry,',
    '    coordinator,',
    '    observer,',
    '    adapter,',
    '    modules,',
    '    async start() {',
    "      runtime.transition('booting');",
    '      const report = await orchestrator.boot(modules, order);',
    '      if (report.failures.length > 0) {',
    "        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));",
    '      }',
    '      for (const module of modules) kernel.markStarted(module.name);',
    "      runtime.transition('ready');",
    "      runtime.transition('running');",
    '      engine.start();',
    "      log.info('layer running');",
    '      return report;',
    '    },',
    '    async stop() {',
    "      runtime.transition('draining');",
    '      engine.stop();',
    '      await orchestrator.shutdown(modules);',
    '      for (const module of modules) kernel.markStopped(module.name);',
    "      runtime.transition('stopped');",
    "      log.info('layer stopped');",
    '    },',
    '    health() {',
    '      return {',
    '        ready: kernel.health().ready,',
    '        registered: kernel.health().registered,',
    '        started: kernel.health().started,',
    '        state: runtime.state,',
    '        engine: engine.stats(),',
    '      };',
    '    },',
    '  };',
    '}',
    '',
    'export function bootstrap(overrides?: PolicySet): LayerHandle {',
    '  const handle = createLayer(overrides);',
    '  void handle.start();',
    '  return handle;',
    '}',
    '',
  ].join('\n');
}

/* ---------------------------------------------------------------------------
 * Smoke test template — 10 deterministic checks per layer
 * ------------------------------------------------------------------------- */

function tSmoke(cfg) {
  const P = cfg.modules[9];
  return [
    banner(cfg, 'smoke.ts', 'self-test harness'),
    '',
    "import { createLayer, LAYER, CONTRACTS } from './" + P + ".js';",
    '',
    'interface CheckState {',
    '  checks: number;',
    '  failures: number;',
    '}',
    '',
    'const state: CheckState = { checks: 0, failures: 0 };',
    '',
    'function check(name: string, ok: boolean, detail = \'\'): void {',
    '  state.checks += 1;',
    '  if (ok) {',
    "    console.log('  [PASS] ' + name);",
    '  } else {',
    '    state.failures += 1;',
    "    console.error('  [FAIL] ' + name + (detail ? '  -> ' + detail : ''));",
    '  }',
    '}',
    '',
    'async function main(): Promise<void> {',
    '  const startedAt = Date.now();',
    "  console.log('GENESIS ' + LAYER.id + ' smoke — ' + LAYER.name);",
    '',
    "  check('layer manifest identity', LAYER.id === '" + cfg.id + "' && LAYER.codename === '" + cfg.codename + "', JSON.stringify(LAYER));",
    "  check('layer exposes 4 contracts', CONTRACTS.length === 4, 'contracts=' + CONTRACTS.length);",
    '',
    '  const handle = createLayer({ maxEntities: 8, tickMs: 60000, batchSize: 8, ringSize: 16, quota: 8 });',
    '',
    "  check('kernel registers exactly 10 modules', handle.kernel.size === 10, 'size=' + handle.kernel.size);",
    '',
    '  const report = await handle.start();',
    "  check('orchestrator boots with zero failures', report.failures.length === 0, report.failures.join(','));",
    "  check('kernel health is ready', handle.kernel.health().ready, JSON.stringify(handle.kernel.health()));",
    "  check('runtime reaches running state', handle.runtime.state === 'running', 'state=' + handle.runtime.state);",
    '',
    "  const admitted = handle.controller.admit('smoke');",
    "  check('controller admits in-quota scope', admitted.allowed, admitted.reason);",
    '',
    '  let rejected = false;',
    '  for (let i = 0; i < 64; i += 1) {',
    "    if (!handle.controller.admit('smoke').allowed) { rejected = true; break; }",
    '  }',
    "  check('controller rejects over-quota scope', rejected);",
    '',
    '  let sawTick = false;',
    "  handle.coordinator.on('" + cfg.id + ".engine.tick', () => { sawTick = true; });",
    '',
    "  handle.engine.enqueue(() => { handle.observer.record('work', 1); });",
    '  const done = await handle.engine.tick(8);',
    "  check('engine processes queued work', done >= 1 && handle.engine.stats().errors === 0, 'done=' + done);",
    "  check('engine tick event reaches coordinator', sawTick);",
    "  check('observer records metric', handle.observer.count('work') >= 1, 'count=' + handle.observer.count('work'));",
    '',
    "  for (let i = 0; i < 10; i += 1) handle.registry.set('entity-' + i, i);",
    '  const registry = handle.registry.stats();',
    "  check('registry enforces LRU capacity', registry.size === 8 && registry.evictions >= 2, 'size=' + registry.size + ' evictions=' + registry.evictions);",
    '',
    "  check('adapter accepts contract boundary', handle.adapter.call('" + cfg.id + ".engine.tick').accepted);",
    "  check('adapter probe reports healthy environment', handle.adapter.probe().ok);",
    '',
    '  await handle.stop();',
    "  check('runtime drains to stopped', handle.runtime.state === 'stopped', 'state=' + handle.runtime.state);",
    '',
    '  const elapsedMs = Date.now() - startedAt;',
    '  const passed = state.checks - state.failures;',
    '  const ok = state.failures === 0;',
    "  console.log('LAYER ' + LAYER.id + ' ' + (ok ? 'PASS' : 'FAIL') + ' (' + passed + '/' + state.checks + ') in ' + elapsedMs + 'ms');",
    '  if (!ok) process.exitCode = 1;',
    '}',
    '',
    'void main();',
    '',
  ].join('\n');
}

/* ---------------------------------------------------------------------------
 * README template
 * ------------------------------------------------------------------------- */

const ROLE_LABELS = [
  'kernel — module registry & health',
  'orchestrator — ordered boot + reverse shutdown',
  'runtime — guarded lifecycle state machine',
  'controller — policy enforcement & quotas',
  'engine — bounded work queue + tick loop',
  'registry — O(1) LRU entity store',
  'coordinator — contract-gated message bus',
  'observer — ring-buffered telemetry',
  'adapter — environment probe & boundary calls',
  'platform — composition root & public API',
];

function tReadme(cfg) {
  const rows = cfg.modules
    .map((m, i) => '| ' + (i + 1) + ' | `' + m + '` | ' + ROLE_LABELS[i] + ' |')
    .join('\n');
  return [
    '# GENESIS ' + cfg.id + ' — ' + cfg.name,
    '',
    '> **Mission:** ' + cfg.mission,
    '',
    '> Evolution lineage: depends on `' + cfg.dependsOn.join(', ') + '`.',
    '',
    '## Architecture — 10 core TypeScript modules',
    '',
    '| # | Module | Role |',
    '|---|--------|------|',
    rows,
    '',
    '## Contracts (event topics)',
    '',
    '```',
    cfg.contracts.map((c) => '  ' + c).join('\n'),
    '```',
    '',
    '## Quickstart',
    '',
    '```bash',
    '# materialize / regenerate this layer (idempotent)',
    'node genesis/forge.mjs ' + cfg.id,
    '',
    '# typecheck the whole genesis lineage (strict)',
    'node_modules/.bin/tsc --noEmit -p genesis/tsconfig.json',
    '',
    '# run this layer self-test',
    'bun run genesis/' + cfg.id + '/smoke.ts',
    '',
    '# one-shot bootstrap (Termux / Linux)',
    'bash genesis-' + cfg.id + '-bootstrap.sh --smoke',
    '```',
    '',
    '## Boot a layer in code',
    '',
    '```ts',
    "import { createLayer } from './" + cfg.modules[9] + ".js';",
    '',
    'const layer = createLayer();',
    'const report = await layer.start();',
    'console.log(layer.health(), report.totalMs);',
    'await layer.stop();',
    '```',
    '',
    '## Push workflow',
    '',
    '```bash',
    '# commit this layer + push to GitHub (origin) and GitLab (gitlab)',
    'bash genesis/push-evolution.sh ' + cfg.id,
    '',
    '# or land everything',
    'bash genesis/push-evolution.sh all',
    '```',
    '',
  ].join('\n');
}

/* ---------------------------------------------------------------------------
 * Bootstrap script template (root-level, Termux + Linux)
 * ------------------------------------------------------------------------- */

function tBootstrap(cfg) {
  return [
    '#!/usr/bin/env bash',
    '# =============================================================================',
    '# KLYN AI OS — GENESIS ' + cfg.id + ' — ' + cfg.name,
    '# Bootstrap automation. Compatible with Termux (Android) and Linux.',
    '#',
    '#   Usage:  bash genesis-' + cfg.id + '-bootstrap.sh [--typecheck] [--smoke] [--push]',
    '#   - no flags    : materialize the layer (idempotent, safe to re-run)',
    '#   - --typecheck : also typecheck the whole genesis lineage (tsc -p genesis/tsconfig.json)',
    '#   - --smoke     : also run the layer self-test (bun run genesis/' + cfg.id + '/smoke.ts)',
    '#   - --push      : also commit + push to GitHub (origin) and GitLab (gitlab)',
    '# =============================================================================',
    'set -euo pipefail',
    '',
    'LAYER="' + cfg.id + '"',
    'LAYER_NAME="' + cfg.name + '"',
    'ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
    '',
    'cd "$ROOT_DIR"',
    '',
    'if ! command -v node >/dev/null 2>&1; then',
    '  echo "error: node not found. Install it (Termux: pkg install nodejs-lts, Linux: apt install nodejs)."',
    '  exit 1',
    'fi',
    '',
    'RUN_TYPECHECK=0',
    'RUN_SMOKE=0',
    'RUN_PUSH=0',
    'for flag in "$@"; do',
    '  case "$flag" in',
    '    --typecheck) RUN_TYPECHECK=1 ;;',
    '    --smoke) RUN_SMOKE=1 ;;',
    '    --push) RUN_PUSH=1 ;;',
    '    *) echo "warning: unknown flag \'$flag\'" ;;',
    '  esac',
    'done',
    '',
    'echo "[GENESIS $LAYER] $LAYER_NAME"',
    'echo "[GENESIS $LAYER] bootstrap start: $(date -u +%Y-%m-%dT%H:%M:%SZ)"',
    '',
    '# 1) Materialize the layer via the evolution forge (idempotent)',
    'node genesis/forge.mjs "$LAYER"',
    '',
    '# 2) Optional: typecheck the genesis lineage',
    'if [ "$RUN_TYPECHECK" = "1" ]; then',
    '  if [ -x node_modules/.bin/tsc ]; then',
    '    echo "[GENESIS $LAYER] typecheck: genesis lineage"',
    '    node_modules/.bin/tsc --noEmit -p genesis/tsconfig.json',
    '  else',
    '    echo "[GENESIS $LAYER] warning: typescript not installed; skipping typecheck"',
    '  fi',
    'fi',
    '',
    '# 3) Optional: smoke test the layer',
    'if [ "$RUN_SMOKE" = "1" ]; then',
    '  if command -v bun >/dev/null 2>&1; then',
    '    echo "[GENESIS $LAYER] smoke test"',
    '    bun run "genesis/$LAYER/smoke.ts"',
    '  else',
    '    echo "[GENESIS $LAYER] warning: bun not found; skipping smoke (Termux: pkg install bun)"',
    '  fi',
    'fi',
    '',
    '# 4) Optional: commit + push workflow (GitHub origin + GitLab gitlab)',
    'if [ "$RUN_PUSH" = "1" ]; then',
    '  bash genesis/push-evolution.sh "$LAYER"',
    'fi',
    '',
    'MODULE_COUNT="$(ls genesis/$LAYER/*.ts 2>/dev/null | wc -l)"',
    'echo "[GENESIS $LAYER] bootstrap complete: genesis/$LAYER ($MODULE_COUNT TypeScript modules)"',
    '',
  ].join('\n');
}

/* ---------------------------------------------------------------------------
 * Materialization + verification + CLI
 * ------------------------------------------------------------------------- */

function writeFile(dir, name, content, mode) {
  mkdirSync(dir, { recursive: true });
  const target = join(dir, name);
  writeFileSync(target, content, 'utf8');
  if (mode) chmodSync(target, mode);
}

function materialize(cfg) {
  const dir = join(GENESIS, cfg.id);
  writeFile(dir, cfg.modules[0] + '.ts', tKernel(cfg));
  writeFile(dir, cfg.modules[1] + '.ts', tOrchestrator(cfg));
  writeFile(dir, cfg.modules[2] + '.ts', tRuntime(cfg));
  writeFile(dir, cfg.modules[3] + '.ts', tController(cfg));
  writeFile(dir, cfg.modules[4] + '.ts', tEngine(cfg));
  writeFile(dir, cfg.modules[5] + '.ts', tRegistry(cfg));
  writeFile(dir, cfg.modules[6] + '.ts', tCoordinator(cfg));
  writeFile(dir, cfg.modules[7] + '.ts', tObserver(cfg));
  writeFile(dir, cfg.modules[8] + '.ts', tAdapter(cfg));
  writeFile(dir, cfg.modules[9] + '.ts', tPlatform(cfg));
  writeFile(dir, 'smoke.ts', tSmoke(cfg));
  writeFile(dir, 'layer.json', JSON.stringify(cfg, null, 2));
  writeFile(dir, 'README.md', tReadme(cfg));
  writeFile(ROOT, 'genesis-' + cfg.id + '-bootstrap.sh', tBootstrap(cfg), 0o755);
  return 'genesis/' + cfg.id + ' (10 modules + smoke.ts + layer.json + README.md) + genesis-' + cfg.id + '-bootstrap.sh';
}

function verifyLayer(cfg) {
  const dir = join(GENESIS, cfg.id);
  const missing = [];
  if (!existsSync(dir)) return { ok: false, reason: 'missing directory genesis/' + cfg.id };
  for (const name of cfg.modules) {
    if (!existsSync(join(dir, name + '.ts'))) missing.push(name + '.ts');
  }
  for (const extra of ['smoke.ts', 'layer.json', 'README.md']) {
    if (!existsSync(join(dir, extra))) missing.push(extra);
  }
  if (!existsSync(join(ROOT, 'genesis-' + cfg.id + '-bootstrap.sh'))) missing.push('genesis-' + cfg.id + '-bootstrap.sh');
  const tsFiles = readdirSync(dir).filter((f) => f.endsWith('.ts') && !f.endsWith('smoke.ts'));
  const moduleCount = tsFiles.length;
  if (moduleCount !== 10) missing.push('module count=' + moduleCount + ' (expected 10 core modules)');
  return missing.length === 0 ? { ok: true, reason: '' } : { ok: false, reason: missing.join(', ') };
}

function verifyAll() {
  let passed = 0;
  let failed = 0;
  for (const cfg of manifest) {
    const result = verifyLayer(cfg);
    if (result.ok) {
      passed += 1;
      console.log('PASS  ' + cfg.id + '  genesis/' + cfg.id + ' — 10/10 modules');
    } else {
      failed += 1;
      console.log('FAIL  ' + cfg.id + '  ' + result.reason);
    }
  }
  console.log('forge verify: ' + passed + '/' + (passed + failed) + ' layers OK');
  return failed === 0;
}

function listLayers() {
  console.log('GENESIS EVOLUTION — V671..V700 (' + manifest.length + ' layers)');
  for (const cfg of manifest) {
    console.log('  ' + cfg.id.padEnd(6) + cfg.codename.padEnd(34) + cfg.name);
  }
}

const command = process.argv[2] ?? 'all';

if (command === 'list') {
  listLayers();
} else if (command === 'verify') {
  process.exitCode = verifyAll() ? 0 : 1;
} else if (command === 'all') {
  for (const cfg of manifest) {
    const summary = materialize(cfg);
    console.log('forge: materialized ' + summary);
  }
  console.log('');
  process.exitCode = verifyAll() ? 0 : 1;
} else {
  const cfg = manifest.find((layer) => layer.id === command);
  if (!cfg) {
    console.error('error: unknown layer "' + command + '" (expected one of: all | verify | list | v671..v700)');
    process.exitCode = 1;
  } else {
    const summary = materialize(cfg);
    console.log('forge: materialized ' + summary);
    const result = verifyLayer(cfg);
    console.log(result.ok ? 'forge: ' + cfg.id + ' verify PASS' : 'forge: ' + cfg.id + ' verify FAIL: ' + result.reason);
    process.exitCode = result.ok ? 0 : 1;
  }
}
