#!/usr/bin/env bash
# =============================================================================
# KLYN AI OS — GENESIS EVOLUTION PUSH WORKFLOW
# File: genesis/push-evolution.sh
#
# Commits a single evolution layer (or all V671-V700 layers) with the
# canonical commit message from genesis/evolution-manifest.json, then pushes
# to GitHub (remote: origin) and GitLab (remote: gitlab) when configured.
#
#   Usage:  bash genesis/push-evolution.sh [v671|v700|all] [--dry-run]
#   - default: all layers, single commit
#   - --dry-run: show what would be committed and pushed, touch nothing
#
# Compatible with Termux and Linux. Requires: git, node.
# =============================================================================
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

LAYERS_ARG="${1:-all}"
DRY_RUN=0
if [ "${2:-}" = "--dry-run" ]; then
  DRY_RUN=1
fi

if ! command -v node >/dev/null 2>&1; then
  echo "error: node not found (required to read the evolution manifest)."
  exit 1
fi

ids="$(node -e 'const m=require("./genesis/evolution-manifest.json");process.stdout.write(m.map(l=>l.id).join(" "))')"

if [ "$LAYERS_ARG" != "all" ]; then
  case " $ids " in
    *" $LAYERS_ARG "*)
      ids="$LAYERS_ARG"
      ;;
    *)
      echo "error: unknown layer '$LAYERS_ARG' (expected one of: all | $ids)"
      exit 1
      ;;
  esac
fi

commit_layer() {
  local id="$1"
  local message
  message="$(node -e 'const l=require("./genesis/evolution-manifest.json").find(x=>x.id===process.argv[1]);if(!l){console.error("layer not found: "+process.argv[1]);process.exit(1)}process.stdout.write(l.commitMessage)' "$id")"

  if [ "$DRY_RUN" = "1" ]; then
    echo "[push-evolution] [dry-run] would commit: $message"
  else
    git add "genesis/$id" "genesis-$id-bootstrap.sh"
    git commit -m "$message" || echo "[push-evolution] nothing new to commit for $id"
  fi

  for remote in origin gitlab; do
    if git remote | grep -qx "$remote"; then
      if [ "$DRY_RUN" = "1" ]; then
        echo "[push-evolution] [dry-run] would push $remote main"
      else
        echo "[push-evolution] pushing $id -> $remote main"
        git push "$remote" main
      fi
    else
      echo "[push-evolution] remote '$remote' not configured; skipping"
    fi
  done
}

if [ "$LAYERS_ARG" = "all" ]; then
  echo "[push-evolution] staging full genesis evolution (V671-V700)"
  if [ "$DRY_RUN" = "1" ]; then
    echo "[push-evolution] [dry-run] would stage: genesis/ + genesis-v6[7-9][0-9]-bootstrap.sh + genesis-v700-bootstrap.sh"
    echo "[push-evolution] [dry-run] would commit: feat(genesis): v671-v700 evolution layers — complete autonomous AI engineering civilization platform"
    echo "[push-evolution] [dry-run] would push: origin main + gitlab main"
  else
    git add genesis/ genesis-v6[7-9][0-9]-bootstrap.sh genesis-v700-bootstrap.sh
    git commit -m "feat(genesis): v671-v700 evolution layers — complete autonomous AI engineering civilization platform" \
      -m "30 evolution layers (V671-V700), 10 core TypeScript modules each, generated by genesis/forge.mjs from genesis/evolution-manifest.json. Per-layer bootstrap scripts (genesis-vXXX-bootstrap.sh), strict genesis/tsconfig.json, evolution runner (genesis/evolution.ts), and push workflow (genesis/push-evolution.sh)." \
      || echo "[push-evolution] nothing new to commit"
    for remote in origin gitlab; do
      if git remote | grep -qx "$remote"; then
        echo "[push-evolution] pushing genesis evolution -> $remote main"
        git push "$remote" main
      else
        echo "[push-evolution] remote '$remote' not configured; skipping"
      fi
    done
  fi
else
  commit_layer "$LAYERS_ARG"
fi

echo "[push-evolution] done ($([ "$DRY_RUN" = "1" ] && echo 'dry-run' || echo 'live'))"
