/**
 * =============================================================================
 * KLYN AI OS — GENESIS v678 — Autonomous Knowledge Economy Layer
 * Module: KnowledgeMarketAdapter.ts (role: adapter)
 * Mission: Price, exchange, and compound knowledge as the primary economic asset of the civilization.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v678` to regenerate.
 * =============================================================================
 */

import { Logger, monotonic } from '../platform/modules.js';
import type { LayerModule } from '../platform/modules.js';

export interface ProbeCheck {
  name: string;
  ok: boolean;
  detail: string;
}

export interface ProbeResult {
  ok: boolean;
  latencyMs: number;
  checks: ProbeCheck[];
}

export interface CallResult {
  boundary: string;
  accepted: boolean;
  reason: string;
}

export class KnowledgeMarketAdapter implements LayerModule {
  readonly name = 'KnowledgeMarketAdapter';
  readonly role = 'adapter';
  readonly layer: string;
  readonly #boundaries: ReadonlySet<string>;
  readonly #log: Logger;

  constructor(layer: string, boundaries: readonly string[], quiet = false) {
    this.layer = layer;
    this.#boundaries = new Set(boundaries);
    this.#log = new Logger(layer + ':' + this.role, quiet ? 3 : 1);
  }

  start(): void {}
  stop(): void {}

  probe(): ProbeResult {
    const startedAt = monotonic();
    const checks: ProbeCheck[] = [];
    const nodeVersion = typeof process !== 'undefined' ? process.version : 'unknown';
    checks.push({ name: 'node-runtime', ok: nodeVersion !== 'unknown', detail: nodeVersion });
    const home = typeof process !== 'undefined' ? process.env.HOME || process.env.USERPROFILE || '' : '';
    checks.push({ name: 'home-directory', ok: home.length > 0, detail: home || 'unset' });
    checks.push({
      name: 'working-directory',
      ok: typeof process !== 'undefined' && typeof process.cwd === 'function',
      detail: typeof process !== 'undefined' ? process.cwd() : 'n/a',
    });
    checks.push({ name: 'layer-contracts', ok: this.#boundaries.size > 0, detail: String(this.#boundaries.size) });
    const latencyMs = Math.round((monotonic() - startedAt) * 1000) / 1000;
    const ok = checks.every((check) => check.ok);
    if (!ok) this.#log.warn('environment probe reported failures');
    return { ok, latencyMs, checks };
  }

  call(boundary: string, payload?: unknown): CallResult {
    const accepted = this.#boundaries.has(boundary);
    if (accepted && payload !== undefined) this.#log.info('call accepted on ' + boundary);
    return { boundary, accepted, reason: accepted ? 'ok' : 'unknown boundary: ' + boundary };
  }

  boundaries(): string[] {
    return [...this.#boundaries];
  }
}
