import asyncio
import base64
import json
import logging
import time
import uuid
import os
import urllib.request
import urllib.error
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Set

# --- 1. ENTERPRISE TELEMETRY CONFIGURATION ---
class JSONFormatter(logging.Formatter):
    def format(self, record):
        return json.dumps({
            "timestamp": self.formatTime(record, self.datefmt),
            "level": record.levelname,
            "message": record.getMessage()
        })

logger = logging.getLogger("KlynEnterprise")
logger.setLevel(logging.INFO)
ch = logging.StreamHandler()
ch.setFormatter(JSONFormatter())
logger.addHandler(ch)

# --- 2. STRUCTURAL DATA ARCHITECTURE ---
class TaskStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"

@dataclass
class DAGTask:
    id: str
    action: str
    assigned_agent: str
    file_target: str
    instruction: str                  
    dependencies: List[str] = field(default_factory=list)
    status: TaskStatus = TaskStatus.PENDING
    output: Optional[str] = None

# --- 3. BASE64 PROTECTED MULTI-MODEL BRIDGE (V4.3) ---
class LLMBridge:
    def __init__(self):
        self.klyn_api_url = self._sanitize_string(os.getenv("KLYN_API_URL"))
        # Base64 encoded strings to completely bypass string parsing bugs
        self._ds_b64 = "aHR0cHM6Ly9hcGkuZGVlcHNlZWsuY29tL3YxL2NoYXQvY29tcGxldGlvbnM="
        # https://api.openai.com/v1/chat/completions
        self._oa_b64 = "aHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MS9jaGF0L2NvbXBsZXRpb25z"
        # https://generativelanguage.googleapis.com/v1beta/openai/chat/completions
        self._gm_b64 = "aHR0cHM6Ly9nZW5lcmF0aXZlbGFuZ3VhZ2UuZ29vZ2xlYXBpcy5jb20vdjFiZXRhL29wZW5haS9jaGF0L2NvbXBsZXRpb25z"

    def _decode_url(self, b64_str: str) -> str:
        return base64.b64decode(b64_str.encode('utf-8')).decode('utf-8')

    def _sanitize_string(self, val: Optional[str]) -> str:
        if not val:
            return ""
        return val.strip().lstrip('[').rstrip(']').strip("'\" ")

    def resolve_provider_context(self, agent_name: str) -> tuple:
        if agent_name == "Infra_Agent":
            model = self._sanitize_string(os.getenv("DEEPSEEK_MODEL", "deepseek-r1"))
            key = self._sanitize_string(os.getenv("DEEPSEEK_API_KEY", os.getenv("OPENAI_API_KEY", "mock-key")))
            url = self.klyn_api_url or self._decode_url(self._ds_b64)
            return model, key, url
            
        elif agent_name == "Architect_Agent":
            model = self._sanitize_string(os.getenv("GEMINI_MODEL", "gemini-3.1-pro"))
            key = self._sanitize_string(os.getenv("GEMINI_API_KEY", os.getenv("OPENAI_API_KEY", "mock-key")))
            url = self.klyn_api_url or self._decode_url(self._gm_b64)
            return model, key, url
            
        else: 
            model = self._sanitize_string(os.getenv("KLYN_MODEL", "gpt-5.5-pro"))
            key = self._sanitize_string(os.getenv("OPENAI_API_KEY", "mock-key"))
            url = self.klyn_api_url or self._decode_url(self._oa_b64)
            return model, key, url

    async def generate_code(self, agent_name: str, file_target: str, instruction: str, context: str) -> str:
        target_model, api_key, api_url = self.resolve_provider_context(agent_name)
        
        if api_key == "mock-key" or "your_actual" in api_key:
            logger.warning(f"Using fallback compilation engine for {file_target} (Offline Mode)")
            return f"# Autogenerated by KLYN Mock Compiler\n# Target: {file_target}\n# Optimized Via: {target_model}\n\ndef init_module():\n    pass"

        prompt = (
            f"You are the elite specialized tool '{agent_name}' running inside KLYN AI OS matrix via {target_model}.\n"
            f"Your dedicated task is to compile the source code file: {file_target}\n"
            f"User Core Instruction: {instruction}\n"
            f"Upstream System Context/Dependencies: {context}\n\n"
            f"CRITICAL: Return ONLY valid, execution-ready source code. No markdown blocks, backticks (```), or explanations."
        )

        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }
        data = json.dumps({
            "model": target_model,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.15
        }).encode("utf-8")

        req = urllib.request.Request(api_url, data=data, headers=headers, method="POST")
        try:
            response = await asyncio.to_thread(urllib.request.urlopen, req, timeout=45)
            res_data = json.loads(response.read().decode("utf-8"))
            return res_data["choices"][0]["message"]["content"].strip()
        except urllib.error.HTTPError as e:
            if e.code in [402, 401]:
                fallback_model = self._sanitize_string(os.getenv("KLYN_MODEL", "gpt-5.5-pro"))
                openai_key = self._sanitize_string(os.getenv("OPENAI_API_KEY", "mock-key"))
                openai_url = self.klyn_api_url or self._decode_url(self._oa_b64)
                
                logger.warning(f"⚠️ Provider Alert ({e.code}) on {target_model}. Hot-swapping to Clean Endpoint: {openai_url}")
                
                headers["Authorization"] = f"Bearer {openai_key}"
                fallback_data = json.dumps({
                    "model": fallback_model,
                    "messages": [{"role": "user", "content": prompt.replace(target_model, fallback_model)}],
                    "temperature": 0.15
                }).encode("utf-8")
                
                req_fallback = urllib.request.Request(openai_url, data=fallback_data, headers=headers, method="POST")
                try:
                    res_fb = await asyncio.to_thread(urllib.request.urlopen, req_fallback, timeout=45)
                    res_data_fb = json.loads(res_fb.read().decode("utf-8"))
                    logger.info(f"🟢 Failover Clear! Asset generated via core matrix ({fallback_model})")
                    return res_data_fb["choices"][0]["message"]["content"].strip()
                except Exception as inner_e:
                    logger.error(f"Critical System Failure: Both lines disrupted. Telemetry: {str(inner_e)}")
                    raise inner_e
            else:
                raise
        except Exception as general_e:
            logger.error(f"Network routing anomaly on engine {target_model}: {str(general_e)}")
            raise

# --- 4. CORE OPERATIONAL KERNEL ---
class KlynKernel:
    def __init__(self, event_bus: Any, llm: LLMBridge, state_file: str = "klyn_state.json"):
        self.event_bus = event_bus
        self.llm = llm
        self.state_registry: Dict[str, DAGTask] = {}
        self.state_file = os.path.expanduser(f"~/klyn-ai-os/{state_file}")
        self.workspace_dir = os.path.expanduser("~/klyn-workspace")
        self._lock = asyncio.Lock()
        
        os.makedirs(self.workspace_dir, exist_ok=True)
        self.event_bus.subscribe("TASK_FINISHED", self._on_task_event)

    async def _save_state(self):
        async with self._lock:
            state_data = {k: asdict(v) for k, v in self.state_registry.items()}
            with open(self.state_file, 'w') as f:
                json.dump(state_data, f, indent=2)

    async def initialize_workflow(self, raw_tasks: List[Dict[str, Any]]):
        logger.info("Assembling Heterogeneous Multi-Model Graph...")
        for t in raw_tasks:
            task = DAGTask(
                id=t["id"], 
                action=t["action"], 
                assigned_agent=t["assigned_agent"],
                file_target=t["file_target"],
                instruction=t["instruction"],
                dependencies=t.get("dependencies", [])
            )
            self.state_registry[task.id] = task

        await self._save_state()
        await self._orchestrate_next_layer()

    async def _orchestrate_next_layer(self):
        runnable_tasks: List[DAGTask] = []
        async with self._lock:
            for task in self.state_registry.values():
                if task.status != TaskStatus.PENDING:
                    continue
                if all(self.state_registry[d].status == TaskStatus.COMPLETED for d in task.dependencies):
                    runnable_tasks.append(task)

        exec_tasks = [asyncio.create_task(self._execute_agent_vector(task)) for task in runnable_tasks]
        if exec_tasks: await asyncio.gather(*exec_tasks)

    async def _execute_agent_vector(self, task: DAGTask):
        task.status = TaskStatus.RUNNING
        await self._save_state()

        try:
            context_summary = {}
            for dep_id in task.dependencies:
                dep_task = self.state_registry.get(dep_id)
                if dep_task:
                    context_summary[dep_task.file_target] = f"Completed upstream asset via {dep_task.assigned_agent}"

            compiled_code = await self.llm.generate_code(
                agent_name=task.assigned_agent,
                file_target=task.file_target,
                instruction=task.instruction,
                context=json.dumps(context_summary)
            )
            
            target_path = os.path.join(self.workspace_dir, task.file_target)
            os.makedirs(os.path.dirname(target_path), exist_ok=True)
            
            with open(target_path, "w") as f:
                f.write(compiled_code)
            
            task.status = TaskStatus.COMPLETED
            task.output = f"Compiled successfully"
            
            await self.event_bus.publish("TASK_FINISHED", task.assigned_agent, {"task_id": task.id})
        except Exception as e:
            task.status = TaskStatus.FAILED
            await self.event_bus.publish("TASK_FAILED", "Kernel", {"task_id": task.id, "error": str(e)})

    async def _on_task_event(self, event: Any):
        await self._save_state()
        await self._orchestrate_next_layer()

# --- 5. SYSTEM ENVIRONMENT RESOURCING ---
class CoreEventBus:
    def __init__(self):
        self._listeners: Dict[str, List[Callable]] = {}

    def subscribe(self, event_type: str, callback: Callable):
        if event_type not in self._listeners:
            self._listeners[event_type] = []
        self._listeners[event_type].append(callback)

    async def publish(self, event_type: str, sender: str, payload: Dict[str, Any]):
        if event_type in self._listeners:
            tasks = [asyncio.create_task(cb(None)) for cb in self._listeners[event_type]]
            if tasks: await asyncio.gather(*tasks, return_exceptions=True)

async def boot_os():
    bus = CoreEventBus()
    llm = LLMBridge()
    kernel = KlynKernel(bus, llm)
    
    heterogeneous_blueprint = [
        {
            "id": "init_db", 
            "action": "Generate Optimized DB Shards", 
            "assigned_agent": "Infra_Agent",
            "file_target": "config/database.py",
            "instruction": "Design a high-throughput connection pool with asyncpg and auto-reconnection algorithms.",
            "dependencies": []
        },
        {
            "id": "write_api", 
            "action": "Build Core API Framework", 
            "assigned_agent": "Coder_Agent",
            "file_target": "app/main.py",
            "instruction": "Build a scalable FastAPI controller that maps standard router channels and registers global lifecycle events.",
            "dependencies": ["init_db"]
        }
    ]
    
    await kernel.initialize_workflow(heterogeneous_blueprint)

if __name__ == "__main__":
    asyncio.run(boot_os())
