/**
 * =============================================================================
 * KLYN AI OS — GENESIS v692 — Self-Optimizing Infrastructure Layer
 * Module: SelfOptimizingInfrastructurePlatform.ts (role: platform — composition root)
 * Mission: Infrastructure that continuously tunes itself against live workload telemetry.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v692` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { SelfOptimizingInfrastructureKernel } from './SelfOptimizingInfrastructureKernel.js';
import { OptimizationOrchestrator } from './OptimizationOrchestrator.js';
import { SelfOptimizingRuntime } from './SelfOptimizingRuntime.js';
import { OptimizationGovernanceController } from './OptimizationGovernanceController.js';
import { ResourceTuningEngine } from './ResourceTuningEngine.js';
import { OptimizationStateRegistry } from './OptimizationStateRegistry.js';
import { OptimizationCoordinationHub } from './OptimizationCoordinationHub.js';
import { OptimizationTelemetryObserver } from './OptimizationTelemetryObserver.js';
import { HardwareTuningAdapter } from './HardwareTuningAdapter.js';
import type { BootReport } from './OptimizationOrchestrator.js';
import type { EngineStats } from './ResourceTuningEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v692',
  name: 'Self-Optimizing Infrastructure Layer',
  codename: 'SelfOptimizingInfrastructure',
  version: 'V692',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v692.engine.tick', 'v692.tuning.applied', 'v692.gain.verified', 'v692.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 8192,
      tickMs: 16,
      batchSize: 128,
      ringSize: 1024,
      consensusThreshold: 0.75,
      compactionThreshold: 0.3,
      quota: 4096,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: SelfOptimizingInfrastructureKernel;
  orchestrator: OptimizationOrchestrator;
  runtime: SelfOptimizingRuntime;
  controller: OptimizationGovernanceController;
  engine: ResourceTuningEngine;
  registry: OptimizationStateRegistry;
  coordinator: OptimizationCoordinationHub;
  observer: OptimizationTelemetryObserver;
  adapter: HardwareTuningAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class SelfOptimizingInfrastructurePlatform implements LayerModule {
  readonly name = 'SelfOptimizingInfrastructurePlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new SelfOptimizingInfrastructureKernel(layer, LAYER.codename);
  const orchestrator = new OptimizationOrchestrator(layer);
  const runtime = new SelfOptimizingRuntime(layer);
  const controller = new OptimizationGovernanceController(layer, policies);
  const coordinator = new OptimizationCoordinationHub(layer, CONTRACTS, bus);
  const engine = new ResourceTuningEngine(layer, policies, bus);
  const registry = new OptimizationStateRegistry(layer, policies.maxEntities);
  const observer = new OptimizationTelemetryObserver(layer, policies.ringSize);
  const adapter = new HardwareTuningAdapter(layer, CONTRACTS);
  const platform = new SelfOptimizingInfrastructurePlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
