[package]
name = "klyn_kernel_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candle-core = { version = "0.9.0", default-features = false }
candle-transformers = { version = "0.9.0", default-features = false }
candle-nn = "0.9.0"
napi = { version = "2.13.3", features = ["async", "napi9", "tokio_rt"] }
napi-derive = "2.13.3"
tokenizers = { version = "0.15.2", default-features = false, features = ["onig"] }
memmap2 = "0.9.0"
parking_lot = "0.12.1"
zerocopy = { version = "0.7", features = ["derive"] }
tokio = { version = "1.38", features = ["full"] }

[build-dependencies]
napi-build = "2.3.2"
