/**
 * =============================================================================
 * KLYN AI OS — GENESIS v695 — Universal Intelligence Platform Layer
 * Module: UniversalIntelligencePlatform.ts (role: platform — composition root)
 * Mission: One platform exposing every intelligence capability as a uniform, composable service.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v695` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { UniversalIntelligenceKernel } from './UniversalIntelligenceKernel.js';
import { UniversalIntelligenceOrchestrator } from './UniversalIntelligenceOrchestrator.js';
import { UniversalIntelligenceRuntime } from './UniversalIntelligenceRuntime.js';
import { UniversalGovernanceController } from './UniversalGovernanceController.js';
import { UnifiedIntelligenceEngine } from './UnifiedIntelligenceEngine.js';
import { UniversalIntelligenceRegistry } from './UniversalIntelligenceRegistry.js';
import { UniversalCoordinationHub } from './UniversalCoordinationHub.js';
import { UniversalTelemetryObserver } from './UniversalTelemetryObserver.js';
import { UniversalIntegrationAdapter } from './UniversalIntegrationAdapter.js';
import type { BootReport } from './UniversalIntelligenceOrchestrator.js';
import type { EngineStats } from './UnifiedIntelligenceEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v695',
  name: 'Universal Intelligence Platform Layer',
  codename: 'UniversalIntelligence',
  version: 'V695',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v695.engine.tick', 'v695.capability.resolved', 'v695.fallback.engaged', 'v695.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 32768,
      tickMs: 12,
      batchSize: 192,
      ringSize: 2048,
      consensusThreshold: 0.8,
      compactionThreshold: 0.3,
      quota: 16384,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: UniversalIntelligenceKernel;
  orchestrator: UniversalIntelligenceOrchestrator;
  runtime: UniversalIntelligenceRuntime;
  controller: UniversalGovernanceController;
  engine: UnifiedIntelligenceEngine;
  registry: UniversalIntelligenceRegistry;
  coordinator: UniversalCoordinationHub;
  observer: UniversalTelemetryObserver;
  adapter: UniversalIntegrationAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class UniversalIntelligencePlatform implements LayerModule {
  readonly name = 'UniversalIntelligencePlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new UniversalIntelligenceKernel(layer, LAYER.codename);
  const orchestrator = new UniversalIntelligenceOrchestrator(layer);
  const runtime = new UniversalIntelligenceRuntime(layer);
  const controller = new UniversalGovernanceController(layer, policies);
  const coordinator = new UniversalCoordinationHub(layer, CONTRACTS, bus);
  const engine = new UnifiedIntelligenceEngine(layer, policies, bus);
  const registry = new UniversalIntelligenceRegistry(layer, policies.maxEntities);
  const observer = new UniversalTelemetryObserver(layer, policies.ringSize);
  const adapter = new UniversalIntegrationAdapter(layer, CONTRACTS);
  const platform = new UniversalIntelligencePlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
