/**
 * =============================================================================
 * KLYN AI OS — GENESIS v677 — Advanced Cognitive Computing Layer
 * Module: AdvancedCognitivePlatform.ts (role: platform — composition root)
 * Mission: Deliver structured cognition pipelines: perception, reasoning, memory, and judgment as primitives.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v677` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { CognitiveComputingKernel } from './CognitiveComputingKernel.js';
import { CognitivePipelineOrchestrator } from './CognitivePipelineOrchestrator.js';
import { CognitiveComputingRuntime } from './CognitiveComputingRuntime.js';
import { CognitionGovernanceController } from './CognitionGovernanceController.js';
import { CognitiveInferenceEngine } from './CognitiveInferenceEngine.js';
import { KnowledgeStateRegistry } from './KnowledgeStateRegistry.js';
import { CognitiveCoordinationHub } from './CognitiveCoordinationHub.js';
import { CognitionTelemetryObserver } from './CognitionTelemetryObserver.js';
import { CognitiveHardwareAdapter } from './CognitiveHardwareAdapter.js';
import type { BootReport } from './CognitivePipelineOrchestrator.js';
import type { EngineStats } from './CognitiveInferenceEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v677',
  name: 'Advanced Cognitive Computing Layer',
  codename: 'CognitiveComputing',
  version: 'V677',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v677.engine.tick', 'v677.inference.completed', 'v677.knowledge.updated', 'v677.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 8192,
      tickMs: 16,
      batchSize: 128,
      ringSize: 1024,
      consensusThreshold: 0.7,
      compactionThreshold: 0.3,
      quota: 4096,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: CognitiveComputingKernel;
  orchestrator: CognitivePipelineOrchestrator;
  runtime: CognitiveComputingRuntime;
  controller: CognitionGovernanceController;
  engine: CognitiveInferenceEngine;
  registry: KnowledgeStateRegistry;
  coordinator: CognitiveCoordinationHub;
  observer: CognitionTelemetryObserver;
  adapter: CognitiveHardwareAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class AdvancedCognitivePlatform implements LayerModule {
  readonly name = 'AdvancedCognitivePlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new CognitiveComputingKernel(layer, LAYER.codename);
  const orchestrator = new CognitivePipelineOrchestrator(layer);
  const runtime = new CognitiveComputingRuntime(layer);
  const controller = new CognitionGovernanceController(layer, policies);
  const coordinator = new CognitiveCoordinationHub(layer, CONTRACTS, bus);
  const engine = new CognitiveInferenceEngine(layer, policies, bus);
  const registry = new KnowledgeStateRegistry(layer, policies.maxEntities);
  const observer = new CognitionTelemetryObserver(layer, policies.ringSize);
  const adapter = new CognitiveHardwareAdapter(layer, CONTRACTS);
  const platform = new AdvancedCognitivePlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
