/**
 * =============================================================================
 * KLYN AI OS — GENESIS v677 — Advanced Cognitive Computing Layer
 * Module: KnowledgeStateRegistry.ts (role: registry)
 * Mission: Deliver structured cognition pipelines: perception, reasoning, memory, and judgment as primitives.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v677` to regenerate.
 * =============================================================================
 */

import type { LayerModule } from '../platform/modules.js';

export interface RegistryStats {
  capacity: number;
  size: number;
  hits: number;
  misses: number;
  evictions: number;
}

export class KnowledgeStateRegistry<T = unknown> implements LayerModule {
  readonly name = 'KnowledgeStateRegistry';
  readonly role = 'registry';
  readonly layer: string;
  readonly #capacity: number;
  readonly #map = new Map<string, T>();
  #hits = 0;
  #misses = 0;
  #evictions = 0;

  constructor(layer: string, capacity = 1024) {
    this.layer = layer;
    this.#capacity = Math.max(1, capacity | 0);
  }

  start(): void {}
  stop(): void {}

  set(key: string, value: T): void {
    if (this.#map.has(key)) this.#map.delete(key);
    this.#map.set(key, value);
    if (this.#map.size > this.#capacity) {
      const oldest = this.#map.keys().next().value;
      if (oldest !== undefined) {
        this.#map.delete(oldest);
        this.#evictions += 1;
      }
    }
  }

  get(key: string): T | undefined {
    const value = this.#map.get(key);
    if (value === undefined) {
      this.#misses += 1;
      return undefined;
    }
    this.#map.delete(key);
    this.#map.set(key, value);
    this.#hits += 1;
    return value;
  }

  has(key: string): boolean {
    return this.#map.has(key);
  }

  evict(key: string): boolean {
    return this.#map.delete(key);
  }

  clear(): void {
    this.#map.clear();
  }

  get size(): number {
    return this.#map.size;
  }

  snapshot(): Array<[string, T]> {
    return [...this.#map.entries()];
  }

  stats(): RegistryStats {
    return {
      capacity: this.#capacity,
      size: this.#map.size,
      hits: this.#hits,
      misses: this.#misses,
      evictions: this.#evictions,
    };
  }
}
