/**
 * =============================================================================
 * KLYN AI OS — GENESIS v684 — AI Research Civilization Platform Layer
 * Module: AIResearchCivilizationPlatform.ts (role: platform — composition root)
 * Mission: An autonomous research civilization: hypothesis, experiment, publish, and replicate at machine speed.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v684` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { ResearchCivilizationKernel } from './ResearchCivilizationKernel.js';
import { ResearchProgramOrchestrator } from './ResearchProgramOrchestrator.js';
import { ResearchCivilizationRuntime } from './ResearchCivilizationRuntime.js';
import { ResearchGovernanceController } from './ResearchGovernanceController.js';
import { ExperimentExecutionEngine } from './ExperimentExecutionEngine.js';
import { ResearchPublicationRegistry } from './ResearchPublicationRegistry.js';
import { ResearchCoordinationHub } from './ResearchCoordinationHub.js';
import { ResearchTelemetryObserver } from './ResearchTelemetryObserver.js';
import { ComputeClusterAdapter } from './ComputeClusterAdapter.js';
import type { BootReport } from './ResearchProgramOrchestrator.js';
import type { EngineStats } from './ExperimentExecutionEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v684',
  name: 'AI Research Civilization Platform Layer',
  codename: 'ResearchCivilization',
  version: 'V684',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v684.engine.tick', 'v684.experiment.run', 'v684.paper.published', 'v684.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 16384,
      tickMs: 16,
      batchSize: 128,
      ringSize: 1024,
      consensusThreshold: 0.7,
      compactionThreshold: 0.35,
      quota: 8192,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: ResearchCivilizationKernel;
  orchestrator: ResearchProgramOrchestrator;
  runtime: ResearchCivilizationRuntime;
  controller: ResearchGovernanceController;
  engine: ExperimentExecutionEngine;
  registry: ResearchPublicationRegistry;
  coordinator: ResearchCoordinationHub;
  observer: ResearchTelemetryObserver;
  adapter: ComputeClusterAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class AIResearchCivilizationPlatform implements LayerModule {
  readonly name = 'AIResearchCivilizationPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new ResearchCivilizationKernel(layer, LAYER.codename);
  const orchestrator = new ResearchProgramOrchestrator(layer);
  const runtime = new ResearchCivilizationRuntime(layer);
  const controller = new ResearchGovernanceController(layer, policies);
  const coordinator = new ResearchCoordinationHub(layer, CONTRACTS, bus);
  const engine = new ExperimentExecutionEngine(layer, policies, bus);
  const registry = new ResearchPublicationRegistry(layer, policies.maxEntities);
  const observer = new ResearchTelemetryObserver(layer, policies.ringSize);
  const adapter = new ComputeClusterAdapter(layer, CONTRACTS);
  const platform = new AIResearchCivilizationPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
