/**
 * =============================================================================
 * KLYN AI OS — GENESIS v684 — AI Research Civilization Platform Layer
 * Module: ResearchCoordinationHub.ts (role: coordinator)
 * Mission: An autonomous research civilization: hypothesis, experiment, publish, and replicate at machine speed.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v684` to regenerate.
 * =============================================================================
 */

import { EventBus } from '../platform/modules.js';
import type { LayerModule } from '../platform/modules.js';

export type TopicHandler = (payload: unknown) => void;
export type Unsubscribe = () => void;

export class ResearchCoordinationHub implements LayerModule {
  readonly name = 'ResearchCoordinationHub';
  readonly role = 'coordinator';
  readonly layer: string;
  readonly #bus: EventBus;
  readonly #contracts: ReadonlySet<string>;

  constructor(layer: string, contracts: readonly string[], bus: EventBus) {
    this.layer = layer;
    this.#contracts = new Set(contracts);
    this.#bus = bus;
  }

  start(): void {}
  stop(): void {}

  on(topic: string, handler: TopicHandler): Unsubscribe {
    return this.#bus.on(topic, handler);
  }

  emit(topic: string, payload?: unknown): number {
    return this.#bus.emit(topic, payload);
  }

  contracts(): string[] {
    return [...this.#contracts];
  }

  topics(): string[] {
    return this.#bus.topics();
  }

  isContract(topic: string): boolean {
    return this.#contracts.has(topic);
  }

  get delivered(): number {
    return this.#bus.delivered;
  }

  clear(): void {
    this.#bus.clear();
  }
}
