/**
 * =============================================================================
 * KLYN AI OS — GENESIS v684 — AI Research Civilization Platform Layer
 * Module: ResearchGovernanceController.ts (role: controller)
 * Mission: An autonomous research civilization: hypothesis, experiment, publish, and replicate at machine speed.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v684` to regenerate.
 * =============================================================================
 */

import { Logger, TokenBucket } from '../platform/modules.js';
import type { LayerModule, ResolvedPolicies } from '../platform/modules.js';

export interface GateResult {
  allowed: boolean;
  reason: string;
}

export interface PolicySnapshot {
  maxEntities: number;
  tickMs: number;
  batchSize: number;
  ringSize: number;
  consensusThreshold: number;
  compactionThreshold: number;
  quota: number;
}

export class ResearchGovernanceController implements LayerModule {
  readonly name = 'ResearchGovernanceController';
  readonly role = 'controller';
  readonly layer: string;
  readonly #policies: ResolvedPolicies;
  readonly #buckets = new Map<string, TokenBucket>();
  readonly #log: Logger;

  constructor(layer: string, policies: ResolvedPolicies, quiet = false) {
    this.layer = layer;
    this.#policies = policies;
    this.#log = new Logger(layer + ':' + this.role, quiet ? 3 : 1);
  }

  start(): void {}
  stop(): void {}

  policies(): PolicySnapshot {
    return {
      maxEntities: this.#policies.maxEntities,
      tickMs: this.#policies.tickMs,
      batchSize: this.#policies.batchSize,
      ringSize: this.#policies.ringSize,
      consensusThreshold: this.#policies.consensusThreshold,
      compactionThreshold: this.#policies.compactionThreshold,
      quota: this.#policies.quota,
    };
  }

  admit(scope: string, weight = 1): GateResult {
    let bucket = this.#buckets.get(scope);
    if (!bucket) {
      bucket = new TokenBucket(this.#policies.quota, this.#policies.quota / 1000);
      this.#buckets.set(scope, bucket);
    }
    const allowed = bucket.take(weight);
    return { allowed, reason: allowed ? 'ok' : 'quota exceeded: ' + scope };
  }

  requireReady(state: string): GateResult {
    const allowed = state === 'running';
    return { allowed, reason: allowed ? 'ok' : 'layer not ready: ' + state };
  }

  consensus(agree: number, total: number): boolean {
    return total > 0 && agree / total >= this.#policies.consensusThreshold;
  }

  assert(condition: boolean, message: string): void {
    if (!condition) throw new Error('[' + this.layer + '] ' + message);
  }

  reset(): void {
    this.#buckets.clear();
    this.#log.info('quota buckets reset');
  }
}
