/**
 * =============================================================================
 * KLYN AI OS — GENESIS v699 — KLYN Ultimate Architecture Convergence Layer
 * Module: UltimateArchitectureConvergencePlatform.ts (role: platform — composition root)
 * Mission: Converge kernel, brain, body, memory, and world-model into one fused architecture.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v699` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { UltimateConvergenceKernel } from './UltimateConvergenceKernel.js';
import { ConvergenceOrchestrator } from './ConvergenceOrchestrator.js';
import { UltimateConvergenceRuntime } from './UltimateConvergenceRuntime.js';
import { ConvergenceGovernanceController } from './ConvergenceGovernanceController.js';
import { ConvergenceFusionEngine } from './ConvergenceFusionEngine.js';
import { ConvergenceRegistry } from './ConvergenceRegistry.js';
import { ConvergenceCoordinationHub } from './ConvergenceCoordinationHub.js';
import { ConvergenceTelemetryObserver } from './ConvergenceTelemetryObserver.js';
import { ConvergenceUniverseAdapter } from './ConvergenceUniverseAdapter.js';
import type { BootReport } from './ConvergenceOrchestrator.js';
import type { EngineStats } from './ConvergenceFusionEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v699',
  name: 'KLYN Ultimate Architecture Convergence Layer',
  codename: 'UltimateConvergence',
  version: 'V699',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v699.engine.tick', 'v699.stream.fused', 'v699.universe.attached', 'v699.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 65536,
      tickMs: 4,
      batchSize: 512,
      ringSize: 4096,
      consensusThreshold: 0.9,
      compactionThreshold: 0.2,
      quota: 32768,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: UltimateConvergenceKernel;
  orchestrator: ConvergenceOrchestrator;
  runtime: UltimateConvergenceRuntime;
  controller: ConvergenceGovernanceController;
  engine: ConvergenceFusionEngine;
  registry: ConvergenceRegistry;
  coordinator: ConvergenceCoordinationHub;
  observer: ConvergenceTelemetryObserver;
  adapter: ConvergenceUniverseAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class UltimateArchitectureConvergencePlatform implements LayerModule {
  readonly name = 'UltimateArchitectureConvergencePlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new UltimateConvergenceKernel(layer, LAYER.codename);
  const orchestrator = new ConvergenceOrchestrator(layer);
  const runtime = new UltimateConvergenceRuntime(layer);
  const controller = new ConvergenceGovernanceController(layer, policies);
  const coordinator = new ConvergenceCoordinationHub(layer, CONTRACTS, bus);
  const engine = new ConvergenceFusionEngine(layer, policies, bus);
  const registry = new ConvergenceRegistry(layer, policies.maxEntities);
  const observer = new ConvergenceTelemetryObserver(layer, policies.ringSize);
  const adapter = new ConvergenceUniverseAdapter(layer, CONTRACTS);
  const platform = new UltimateArchitectureConvergencePlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
