/**
 * =============================================================================
 * KLYN AI OS — GENESIS v679 — Universal AI Application Runtime Layer
 * Module: UniversalAppRuntimePlatform.ts (role: platform — composition root)
 * Mission: One runtime that hosts, isolates, and executes any AI application on any host.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v679` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { UniversalAppRuntimeKernel } from './UniversalAppRuntimeKernel.js';
import { UniversalAppOrchestrator } from './UniversalAppOrchestrator.js';
import { UniversalApplicationRuntime } from './UniversalApplicationRuntime.js';
import { AppRuntimeGovernanceController } from './AppRuntimeGovernanceController.js';
import { AppExecutionEngine } from './AppExecutionEngine.js';
import { AppInstanceRegistry } from './AppInstanceRegistry.js';
import { AppRuntimeCoordinationHub } from './AppRuntimeCoordinationHub.js';
import { AppRuntimeTelemetryObserver } from './AppRuntimeTelemetryObserver.js';
import { PlatformEnvironmentAdapter } from './PlatformEnvironmentAdapter.js';
import type { BootReport } from './UniversalAppOrchestrator.js';
import type { EngineStats } from './AppExecutionEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v679',
  name: 'Universal AI Application Runtime Layer',
  codename: 'UniversalAppRuntime',
  version: 'V679',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v679.engine.tick', 'v679.app.deployed', 'v679.instance.scaled', 'v679.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 8192,
      tickMs: 16,
      batchSize: 128,
      ringSize: 1024,
      consensusThreshold: 0.7,
      compactionThreshold: 0.35,
      quota: 4096,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: UniversalAppRuntimeKernel;
  orchestrator: UniversalAppOrchestrator;
  runtime: UniversalApplicationRuntime;
  controller: AppRuntimeGovernanceController;
  engine: AppExecutionEngine;
  registry: AppInstanceRegistry;
  coordinator: AppRuntimeCoordinationHub;
  observer: AppRuntimeTelemetryObserver;
  adapter: PlatformEnvironmentAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class UniversalAppRuntimePlatform implements LayerModule {
  readonly name = 'UniversalAppRuntimePlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new UniversalAppRuntimeKernel(layer, LAYER.codename);
  const orchestrator = new UniversalAppOrchestrator(layer);
  const runtime = new UniversalApplicationRuntime(layer);
  const controller = new AppRuntimeGovernanceController(layer, policies);
  const coordinator = new AppRuntimeCoordinationHub(layer, CONTRACTS, bus);
  const engine = new AppExecutionEngine(layer, policies, bus);
  const registry = new AppInstanceRegistry(layer, policies.maxEntities);
  const observer = new AppRuntimeTelemetryObserver(layer, policies.ringSize);
  const adapter = new PlatformEnvironmentAdapter(layer, CONTRACTS);
  const platform = new UniversalAppRuntimePlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
