/**
 * =============================================================================
 * KLYN AI OS — GENESIS v680 — KLYN Intelligent Cloud Platform Layer
 * Module: IntelligentCloudPlatform.ts (role: platform — composition root)
 * Mission: A self-driving cloud control plane that provisions, routes, and rebalances capacity without humans.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v680` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { IntelligentCloudKernel } from './IntelligentCloudKernel.js';
import { CloudControlPlaneOrchestrator } from './CloudControlPlaneOrchestrator.js';
import { IntelligentCloudRuntime } from './IntelligentCloudRuntime.js';
import { CloudGovernanceController } from './CloudGovernanceController.js';
import { CloudWorkloadEngine } from './CloudWorkloadEngine.js';
import { CloudResourceRegistry } from './CloudResourceRegistry.js';
import { CloudCoordinationHub } from './CloudCoordinationHub.js';
import { CloudTelemetryObserver } from './CloudTelemetryObserver.js';
import { CloudProviderAdapter } from './CloudProviderAdapter.js';
import type { BootReport } from './CloudControlPlaneOrchestrator.js';
import type { EngineStats } from './CloudWorkloadEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v680',
  name: 'KLYN Intelligent Cloud Platform Layer',
  codename: 'IntelligentCloud',
  version: 'V680',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v680.engine.tick', 'v680.workload.scheduled', 'v680.capacity.rebalanced', 'v680.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 32768,
      tickMs: 12,
      batchSize: 192,
      ringSize: 2048,
      consensusThreshold: 0.66,
      compactionThreshold: 0.3,
      quota: 8192,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: IntelligentCloudKernel;
  orchestrator: CloudControlPlaneOrchestrator;
  runtime: IntelligentCloudRuntime;
  controller: CloudGovernanceController;
  engine: CloudWorkloadEngine;
  registry: CloudResourceRegistry;
  coordinator: CloudCoordinationHub;
  observer: CloudTelemetryObserver;
  adapter: CloudProviderAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class IntelligentCloudPlatform implements LayerModule {
  readonly name = 'IntelligentCloudPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new IntelligentCloudKernel(layer, LAYER.codename);
  const orchestrator = new CloudControlPlaneOrchestrator(layer);
  const runtime = new IntelligentCloudRuntime(layer);
  const controller = new CloudGovernanceController(layer, policies);
  const coordinator = new CloudCoordinationHub(layer, CONTRACTS, bus);
  const engine = new CloudWorkloadEngine(layer, policies, bus);
  const registry = new CloudResourceRegistry(layer, policies.maxEntities);
  const observer = new CloudTelemetryObserver(layer, policies.ringSize);
  const adapter = new CloudProviderAdapter(layer, CONTRACTS);
  const platform = new IntelligentCloudPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
