/**
 * =============================================================================
 * KLYN AI OS — GENESIS v682 — AI Infrastructure Automation Layer
 * Module: AIInfrastructureAutomationPlatform.ts (role: platform — composition root)
 * Mission: Declarative infrastructure that provisions, patches, and repairs itself under policy.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v682` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { InfrastructureAutomationKernel } from './InfrastructureAutomationKernel.js';
import { AutomationControlOrchestrator } from './AutomationControlOrchestrator.js';
import { InfrastructureAutomationRuntime } from './InfrastructureAutomationRuntime.js';
import { AutomationGovernanceController } from './AutomationGovernanceController.js';
import { ProvisioningEngine } from './ProvisioningEngine.js';
import { InfrastructureStateRegistry } from './InfrastructureStateRegistry.js';
import { AutomationCoordinationHub } from './AutomationCoordinationHub.js';
import { AutomationTelemetryObserver } from './AutomationTelemetryObserver.js';
import { InfrastructureSystemAdapter } from './InfrastructureSystemAdapter.js';
import type { BootReport } from './AutomationControlOrchestrator.js';
import type { EngineStats } from './ProvisioningEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v682',
  name: 'AI Infrastructure Automation Layer',
  codename: 'InfrastructureAutomation',
  version: 'V682',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v682.engine.tick', 'v682.resource.provisioned', 'v682.drift.corrected', 'v682.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 8192,
      tickMs: 16,
      batchSize: 128,
      ringSize: 1024,
      consensusThreshold: 0.75,
      compactionThreshold: 0.4,
      quota: 4096,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: InfrastructureAutomationKernel;
  orchestrator: AutomationControlOrchestrator;
  runtime: InfrastructureAutomationRuntime;
  controller: AutomationGovernanceController;
  engine: ProvisioningEngine;
  registry: InfrastructureStateRegistry;
  coordinator: AutomationCoordinationHub;
  observer: AutomationTelemetryObserver;
  adapter: InfrastructureSystemAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class AIInfrastructureAutomationPlatform implements LayerModule {
  readonly name = 'AIInfrastructureAutomationPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new InfrastructureAutomationKernel(layer, LAYER.codename);
  const orchestrator = new AutomationControlOrchestrator(layer);
  const runtime = new InfrastructureAutomationRuntime(layer);
  const controller = new AutomationGovernanceController(layer, policies);
  const coordinator = new AutomationCoordinationHub(layer, CONTRACTS, bus);
  const engine = new ProvisioningEngine(layer, policies, bus);
  const registry = new InfrastructureStateRegistry(layer, policies.maxEntities);
  const observer = new AutomationTelemetryObserver(layer, policies.ringSize);
  const adapter = new InfrastructureSystemAdapter(layer, CONTRACTS);
  const platform = new AIInfrastructureAutomationPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
