/**
 * =============================================================================
 * KLYN AI OS — GENESIS v671 — Autonomous Enterprise Civilization Platform Layer
 * Module: AutonomousCivilizationPlatform.ts (role: platform — composition root)
 * Mission: Operate the enterprise as a self-governing civilization of autonomous business units, policies, and value flows.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v671` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { EnterpriseCivilizationKernel } from './EnterpriseCivilizationKernel.js';
import { AutonomousEnterpriseOrchestrator } from './AutonomousEnterpriseOrchestrator.js';
import { EnterpriseCivilizationRuntime } from './EnterpriseCivilizationRuntime.js';
import { CivilizationGovernanceController } from './CivilizationGovernanceController.js';
import { AutonomousOperationsEngine } from './AutonomousOperationsEngine.js';
import { EnterpriseEntityRegistry } from './EnterpriseEntityRegistry.js';
import { CivilizationCoordinationHub } from './CivilizationCoordinationHub.js';
import { EnterpriseTelemetryObserver } from './EnterpriseTelemetryObserver.js';
import { EnterpriseSystemAdapter } from './EnterpriseSystemAdapter.js';
import type { BootReport } from './AutonomousEnterpriseOrchestrator.js';
import type { EngineStats } from './AutonomousOperationsEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v671',
  name: 'Autonomous Enterprise Civilization Platform Layer',
  codename: 'EnterpriseCivilization',
  version: 'V671',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v671.engine.tick', 'v671.unit.provisioned', 'v671.policy.applied', 'v671.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 2048,
      tickMs: 25,
      batchSize: 64,
      ringSize: 512,
      consensusThreshold: 0.75,
      compactionThreshold: 0.5,
      quota: 1024,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: EnterpriseCivilizationKernel;
  orchestrator: AutonomousEnterpriseOrchestrator;
  runtime: EnterpriseCivilizationRuntime;
  controller: CivilizationGovernanceController;
  engine: AutonomousOperationsEngine;
  registry: EnterpriseEntityRegistry;
  coordinator: CivilizationCoordinationHub;
  observer: EnterpriseTelemetryObserver;
  adapter: EnterpriseSystemAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class AutonomousCivilizationPlatform implements LayerModule {
  readonly name = 'AutonomousCivilizationPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new EnterpriseCivilizationKernel(layer, LAYER.codename);
  const orchestrator = new AutonomousEnterpriseOrchestrator(layer);
  const runtime = new EnterpriseCivilizationRuntime(layer);
  const controller = new CivilizationGovernanceController(layer, policies);
  const coordinator = new CivilizationCoordinationHub(layer, CONTRACTS, bus);
  const engine = new AutonomousOperationsEngine(layer, policies, bus);
  const registry = new EnterpriseEntityRegistry(layer, policies.maxEntities);
  const observer = new EnterpriseTelemetryObserver(layer, policies.ringSize);
  const adapter = new EnterpriseSystemAdapter(layer, CONTRACTS);
  const platform = new AutonomousCivilizationPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
