/**
 * =============================================================================
 * KLYN AI OS — GENESIS v693 — Autonomous Innovation Engine Layer
 * Module: AutonomousInnovationPlatform.ts (role: platform — composition root)
 * Mission: A continuous innovation engine: generate hypotheses, prototype, measure, and scale winners.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v693` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { InnovationEngineKernel } from './InnovationEngineKernel.js';
import { InnovationPipelineOrchestrator } from './InnovationPipelineOrchestrator.js';
import { InnovationRuntime } from './InnovationRuntime.js';
import { InnovationGovernanceController } from './InnovationGovernanceController.js';
import { IdeaGenerationEngine } from './IdeaGenerationEngine.js';
import { InnovationPortfolioRegistry } from './InnovationPortfolioRegistry.js';
import { InnovationCoordinationHub } from './InnovationCoordinationHub.js';
import { InnovationTelemetryObserver } from './InnovationTelemetryObserver.js';
import { ResearchIntegrationAdapter } from './ResearchIntegrationAdapter.js';
import type { BootReport } from './InnovationPipelineOrchestrator.js';
import type { EngineStats } from './IdeaGenerationEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v693',
  name: 'Autonomous Innovation Engine Layer',
  codename: 'InnovationEngine',
  version: 'V693',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v693.engine.tick', 'v693.idea.seeded', 'v693.bet.graduated', 'v693.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 4096,
      tickMs: 20,
      batchSize: 96,
      ringSize: 512,
      consensusThreshold: 0.66,
      compactionThreshold: 0.5,
      quota: 2048,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: InnovationEngineKernel;
  orchestrator: InnovationPipelineOrchestrator;
  runtime: InnovationRuntime;
  controller: InnovationGovernanceController;
  engine: IdeaGenerationEngine;
  registry: InnovationPortfolioRegistry;
  coordinator: InnovationCoordinationHub;
  observer: InnovationTelemetryObserver;
  adapter: ResearchIntegrationAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class AutonomousInnovationPlatform implements LayerModule {
  readonly name = 'AutonomousInnovationPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new InnovationEngineKernel(layer, LAYER.codename);
  const orchestrator = new InnovationPipelineOrchestrator(layer);
  const runtime = new InnovationRuntime(layer);
  const controller = new InnovationGovernanceController(layer, policies);
  const coordinator = new InnovationCoordinationHub(layer, CONTRACTS, bus);
  const engine = new IdeaGenerationEngine(layer, policies, bus);
  const registry = new InnovationPortfolioRegistry(layer, policies.maxEntities);
  const observer = new InnovationTelemetryObserver(layer, policies.ringSize);
  const adapter = new ResearchIntegrationAdapter(layer, CONTRACTS);
  const platform = new AutonomousInnovationPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
