export interface CodeTask {

 file:string;

 requirement:string;

}


export interface GeneratedCode {

 file:string;

 content:string;

}


export class CodeGenerationAgent {


 generate(task:CodeTask):GeneratedCode {


   return {

     file:task.file,

     content:
       `// Generated by KLYN PRIME\n// ${task.requirement}`

   };


 }


}
