/**
 * =============================================================================
 * KLYN AI OS — GENESIS v700 — KLYN Final Evolution Operating System Layer
 * Module: FinalEvolutionOSPlatform.ts (role: platform — composition root)
 * Mission: The final operating system: the complete autonomous AI engineering civilization in one bootable surface.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v700` to regenerate.
 * =============================================================================
 */

import { EventBus, Logger, normalizePolicies } from '../platform/modules.js';
import type { LayerModule, PolicySet } from '../platform/modules.js';

import { FinalEvolutionOSKernel } from './FinalEvolutionOSKernel.js';
import { FinalEvolutionOrchestrator } from './FinalEvolutionOrchestrator.js';
import { FinalEvolutionRuntime } from './FinalEvolutionRuntime.js';
import { FinalGovernanceController } from './FinalGovernanceController.js';
import { FinalExecutionEngine } from './FinalExecutionEngine.js';
import { FinalStateRegistry } from './FinalStateRegistry.js';
import { FinalCoordinationHub } from './FinalCoordinationHub.js';
import { FinalTelemetryObserver } from './FinalTelemetryObserver.js';
import { FinalUniverseAdapter } from './FinalUniverseAdapter.js';
import type { BootReport } from './FinalEvolutionOrchestrator.js';
import type { EngineStats } from './FinalExecutionEngine.js';

export interface LayerInfo {
  id: string;
  name: string;
  codename: string;
  version: string;
}

export const LAYER: LayerInfo = Object.freeze({
  id: 'v700',
  name: 'KLYN Final Evolution Operating System Layer',
  codename: 'FinalEvolutionOS',
  version: 'V700',
});

export const CONTRACTS: readonly string[] = Object.freeze(['v700.engine.tick', 'v700.capability.manifested', 'v700.os.booted', 'v700.metric.recorded']);

const LAYER_POLICIES = {
      maxEntities: 65536,
      tickMs: 4,
      batchSize: 512,
      ringSize: 4096,
      consensusThreshold: 0.95,
      compactionThreshold: 0.2,
      quota: 32768,
    };

export interface LayerHealth {
  ready: boolean;
  registered: number;
  started: number;
  state: string;
  engine: EngineStats;
}

export interface LayerHandle {
  info: LayerInfo;
  kernel: FinalEvolutionOSKernel;
  orchestrator: FinalEvolutionOrchestrator;
  runtime: FinalEvolutionRuntime;
  controller: FinalGovernanceController;
  engine: FinalExecutionEngine;
  registry: FinalStateRegistry;
  coordinator: FinalCoordinationHub;
  observer: FinalTelemetryObserver;
  adapter: FinalUniverseAdapter;
  modules: LayerModule[];
  start(): Promise<BootReport>;
  stop(): Promise<void>;
  health(): LayerHealth;
}

export class FinalEvolutionOSPlatform implements LayerModule {
  readonly name = 'FinalEvolutionOSPlatform';
  readonly role = 'platform';
  readonly layer: string;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* composition root: lifecycle is driven by the layer handle */ }
  stop(): void { /* composition root: lifecycle is driven by the layer handle */ }
}

export function createLayer(overrides?: PolicySet): LayerHandle {
  const policies = normalizePolicies({ ...LAYER_POLICIES, ...(overrides ?? {}) });
  const bus = new EventBus();
  const layer = LAYER.id;
  const log = new Logger(LAYER.id);

  const kernel = new FinalEvolutionOSKernel(layer, LAYER.codename);
  const orchestrator = new FinalEvolutionOrchestrator(layer);
  const runtime = new FinalEvolutionRuntime(layer);
  const controller = new FinalGovernanceController(layer, policies);
  const coordinator = new FinalCoordinationHub(layer, CONTRACTS, bus);
  const engine = new FinalExecutionEngine(layer, policies, bus);
  const registry = new FinalStateRegistry(layer, policies.maxEntities);
  const observer = new FinalTelemetryObserver(layer, policies.ringSize);
  const adapter = new FinalUniverseAdapter(layer, CONTRACTS);
  const platform = new FinalEvolutionOSPlatform(layer);

  const modules: LayerModule[] = [
    kernel, orchestrator, runtime, controller, engine, registry, coordinator, observer, adapter, platform,
  ];
  const order: string[] = modules.map((module) => module.name);
  for (const module of modules) kernel.register(module);

  return {
    info: LAYER,
    kernel,
    orchestrator,
    runtime,
    controller,
    engine,
    registry,
    coordinator,
    observer,
    adapter,
    modules,
    async start() {
      runtime.transition('booting');
      const report = await orchestrator.boot(modules, order);
      if (report.failures.length > 0) {
        throw new Error(layer + ': boot failed: ' + report.failures.join('; '));
      }
      for (const module of modules) kernel.markStarted(module.name);
      runtime.transition('ready');
      runtime.transition('running');
      engine.start();
      log.info('layer running');
      return report;
    },
    async stop() {
      runtime.transition('draining');
      engine.stop();
      await orchestrator.shutdown(modules);
      for (const module of modules) kernel.markStopped(module.name);
      runtime.transition('stopped');
      log.info('layer stopped');
    },
    health() {
      return {
        ready: kernel.health().ready,
        registered: kernel.health().registered,
        started: kernel.health().started,
        state: runtime.state,
        engine: engine.stats(),
      };
    },
  };
}

export function bootstrap(overrides?: PolicySet): LayerHandle {
  const handle = createLayer(overrides);
  void handle.start();
  return handle;
}
