/**
 * =============================================================================
 * KLYN AI OS — GENESIS v700 — KLYN Final Evolution Operating System Layer
 * Module: FinalEvolutionRuntime.ts (role: runtime)
 * Mission: The final operating system: the complete autonomous AI engineering civilization in one bootable surface.
 * Generated by genesis/forge.mjs — re-run `node genesis/forge.mjs v700` to regenerate.
 * =============================================================================
 */

import type { LayerModule } from '../platform/modules.js';

export type RuntimeState = 'idle' | 'booting' | 'ready' | 'running' | 'draining' | 'stopped';

const ALLOWED_TRANSITIONS: Record<RuntimeState, RuntimeState[]> = {
  idle: ['booting'],
  booting: ['ready', 'stopped'],
  ready: ['running', 'stopped'],
  running: ['draining', 'stopped'],
  draining: ['stopped'],
  stopped: [],
};

export class FinalEvolutionRuntime implements LayerModule {
  readonly name = 'FinalEvolutionRuntime';
  readonly role = 'runtime';
  readonly layer: string;
  #state: RuntimeState = 'idle';
  #transitions = new Map<RuntimeState, Set<() => void>>();
  #enteredRunningAt = 0;

  constructor(layer: string) {
    this.layer = layer;
  }

  start(): void { /* lifecycle is driven by the platform handle */ }
  stop(): void { /* lifecycle is driven by the platform handle */ }

  get state(): RuntimeState {
    return this.#state;
  }

  onEnter(state: RuntimeState, callback: () => void): () => void {
    let set = this.#transitions.get(state);
    if (!set) {
      set = new Set();
      this.#transitions.set(state, set);
    }
    set.add(callback);
    return () => {
      if (set) set.delete(callback);
    };
  }

  transition(next: RuntimeState): void {
    const allowed = ALLOWED_TRANSITIONS[this.#state];
    if (!allowed || allowed.indexOf(next) < 0) {
      throw new Error(this.layer + ': illegal transition ' + this.#state + ' -> ' + next);
    }
    this.#state = next;
    if (next === 'running') this.#enteredRunningAt = Date.now();
    const set = this.#transitions.get(next);
    if (set) {
      for (const callback of set) {
        try {
          callback();
        } catch {
          /* subscriber isolation */
        }
      }
    }
  }

  uptimeMs(): number {
    return this.#enteredRunningAt > 0 ? Date.now() - this.#enteredRunningAt : 0;
  }
}
